// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/providers/profile_stats_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nostr_sdk/event.dart' as _i4;
import 'package:openvine/models/video_event.dart' as _i5;
import 'package:openvine/services/social_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SocialService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialService extends _i1.Mock implements _i2.SocialService {
  MockSocialService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> get likedEventIds =>
      (super.noSuchMethod(
            Invocation.getter(#likedEventIds),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  List<String> get followingPubkeys =>
      (super.noSuchMethod(
            Invocation.getter(#followingPubkeys),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<_i2.FollowSet> get followSets =>
      (super.noSuchMethod(
            Invocation.getter(#followSets),
            returnValue: <_i2.FollowSet>[],
          )
          as List<_i2.FollowSet>);

  @override
  bool isLiked(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#isLiked, [eventId]),
            returnValue: false,
          )
          as bool);

  @override
  bool hasReposted(String? eventId, {String? pubkey, String? dTag}) =>
      (super.noSuchMethod(
            Invocation.method(
              #hasReposted,
              [eventId],
              {#pubkey: pubkey, #dTag: dTag},
            ),
            returnValue: false,
          )
          as bool);

  @override
  int? getCachedLikeCount(String? eventId) =>
      (super.noSuchMethod(Invocation.method(#getCachedLikeCount, [eventId]))
          as int?);

  @override
  bool isFollowing(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#isFollowing, [pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, int>? getCachedFollowerStats(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(#getCachedFollowerStats, [pubkey]))
          as Map<String, int>?);

  @override
  _i2.FollowSet? getFollowSetById(String? setId) =>
      (super.noSuchMethod(Invocation.method(#getFollowSetById, [setId]))
          as _i2.FollowSet?);

  @override
  bool isInFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#isInFollowSet, [setId, pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> toggleLike(String? eventId, String? authorPubkey) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [eventId, authorPubkey]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getLikeStatus(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getLikeStatus, [eventId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<_i4.Event>> fetchLikedEvents(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLikedEvents, [pubkey]),
            returnValue: _i3.Future<List<_i4.Event>>.value(<_i4.Event>[]),
          )
          as _i3.Future<List<_i4.Event>>);

  @override
  _i3.Future<void> fetchCurrentUserFollowList() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCurrentUserFollowList, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> followUser(String? pubkeyToFollow) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [pubkeyToFollow]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unfollowUser(String? pubkeyToUnfollow) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [pubkeyToUnfollow]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, int>> getFollowerStats(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowerStats, [pubkey]),
            returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i3.Future<Map<String, int>>);

  @override
  _i3.Future<_i2.FollowSet?> createFollowSet({
    required String? name,
    String? description,
    String? imageUrl,
    List<String>? initialPubkeys = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createFollowSet, [], {
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #initialPubkeys: initialPubkeys,
            }),
            returnValue: _i3.Future<_i2.FollowSet?>.value(),
          )
          as _i3.Future<_i2.FollowSet?>);

  @override
  _i3.Future<bool> addToFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#addToFollowSet, [setId, pubkey]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> removeFromFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromFollowSet, [setId, pubkey]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateFollowSet({
    required String? setId,
    String? name,
    String? description,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateFollowSet, [], {
              #setId: setId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteFollowSet(String? setId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFollowSet, [setId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> getUserVideoCount(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getUserVideoCount, [pubkey]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> getUserTotalLikes(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTotalLikes, [pubkey]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> postComment({
    required String? content,
    required String? rootEventId,
    required String? rootEventAuthorPubkey,
    String? replyToEventId,
    String? replyToAuthorPubkey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postComment, [], {
              #content: content,
              #rootEventId: rootEventId,
              #rootEventAuthorPubkey: rootEventAuthorPubkey,
              #replyToEventId: replyToEventId,
              #replyToAuthorPubkey: replyToAuthorPubkey,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i4.Event> fetchCommentsForEvent(String? rootEventId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCommentsForEvent, [rootEventId]),
            returnValue: _i3.Stream<_i4.Event>.empty(),
          )
          as _i3.Stream<_i4.Event>);

  @override
  _i3.Future<int> getCommentCount(String? rootEventId) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentCount, [rootEventId]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> cancelCommentSubscriptions(String? rootEventId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelCommentSubscriptions, [rootEventId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleRepost(_i5.VideoEvent? videoToRepost) =>
      (super.noSuchMethod(
            Invocation.method(#toggleRepost, [videoToRepost]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> repostEvent(_i4.Event? eventToRepost) =>
      (super.noSuchMethod(
            Invocation.method(#repostEvent, [eventToRepost]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> publishRightToBeForgotten() =>
      (super.noSuchMethod(
            Invocation.method(#publishRightToBeForgotten, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
