// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/providers/video_events_listener_simple_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:nostr_client/nostr_client.dart' as _i2;
import 'package:nostr_sdk/event.dart' as _i9;
import 'package:nostr_sdk/filter.dart' as _i12;
import 'package:nostr_sdk/nostr_sdk.dart' as _i13;
import 'package:openvine/models/video_event.dart' as _i4;
import 'package:openvine/services/age_verification_service.dart' as _i8;
import 'package:openvine/services/content_blocklist_service.dart' as _i7;
import 'package:openvine/services/video_event_service.dart' as _i3;
import 'package:openvine/services/video_filter_builder.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCountResult_0 extends _i1.SmartFake implements _i2.CountResult {
  _FakeCountResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrBroadcastResult_1 extends _i1.SmartFake
    implements _i2.NostrBroadcastResult {
  _FakeNostrBroadcastResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VideoEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoEventService extends _i1.Mock implements _i3.VideoEventService {
  MockVideoEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get shouldFilterAdultContent =>
      (super.noSuchMethod(
            Invocation.getter(#shouldFilterAdultContent),
            returnValue: false,
          )
          as bool);

  @override
  List<_i4.VideoEvent> get homeFeedVideos =>
      (super.noSuchMethod(
            Invocation.getter(#homeFeedVideos),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  List<_i4.VideoEvent> get discoveryVideos =>
      (super.noSuchMethod(
            Invocation.getter(#discoveryVideos),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  List<_i4.VideoEvent> get profileVideos =>
      (super.noSuchMethod(
            Invocation.getter(#profileVideos),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  List<_i4.VideoEvent> get editorialVideos =>
      (super.noSuchMethod(
            Invocation.getter(#editorialVideos),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  List<_i4.VideoEvent> get popularNowVideos =>
      (super.noSuchMethod(
            Invocation.getter(#popularNowVideos),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  List<_i4.VideoEvent> get trendingVideos =>
      (super.noSuchMethod(
            Invocation.getter(#trendingVideos),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  List<_i4.VideoEvent> get allHashtagVideos =>
      (super.noSuchMethod(
            Invocation.getter(#allHashtagVideos),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  List<_i4.VideoEvent> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  List<_i4.VideoEvent> get videoEvents =>
      (super.noSuchMethod(
            Invocation.getter(#videoEvents),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  String get classicVinesPubkey =>
      (super.noSuchMethod(
            Invocation.getter(#classicVinesPubkey),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#classicVinesPubkey),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.VoidCallback addVideoUpdateListener(
    void Function(_i4.VideoEvent)? callback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addVideoUpdateListener, [callback]),
            returnValue: () {},
          )
          as _i6.VoidCallback);

  @override
  void removeVideoUpdateListener(void Function(_i4.VideoEvent)? callback) =>
      super.noSuchMethod(
        Invocation.method(#removeVideoUpdateListener, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  void setBlocklistService(_i7.ContentBlocklistService? blocklistService) =>
      super.noSuchMethod(
        Invocation.method(#setBlocklistService, [blocklistService]),
        returnValueForMissingStub: null,
      );

  @override
  void setAgeVerificationService(
    _i8.AgeVerificationService? ageVerificationService,
  ) => super.noSuchMethod(
    Invocation.method(#setAgeVerificationService, [ageVerificationService]),
    returnValueForMissingStub: null,
  );

  @override
  bool shouldFilterEvent(_i9.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#shouldFilterEvent, [event]),
            returnValue: false,
          )
          as bool);

  @override
  int filterAdultContentFromExistingVideos() =>
      (super.noSuchMethod(
            Invocation.method(#filterAdultContentFromExistingVideos, []),
            returnValue: 0,
          )
          as int);

  @override
  List<_i4.VideoEvent> getVideos(_i3.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getVideos, [type]),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  List<_i4.VideoEvent> hashtagVideos(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#hashtagVideos, [tag]),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  void debugDumpCdnDivineVideoThumbnails() => super.noSuchMethod(
    Invocation.method(#debugDumpCdnDivineVideoThumbnails, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i4.VideoEvent> authorVideos(String? pubkeyHex) =>
      (super.noSuchMethod(
            Invocation.method(#authorVideos, [pubkeyHex]),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  bool isLoadingForSubscription(_i3.SubscriptionType? subscriptionType) =>
      (super.noSuchMethod(
            Invocation.method(#isLoadingForSubscription, [subscriptionType]),
            returnValue: false,
          )
          as bool);

  @override
  bool hasEvents(_i3.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#hasEvents, [type]),
            returnValue: false,
          )
          as bool);

  @override
  int getEventCount(_i3.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getEventCount, [type]),
            returnValue: 0,
          )
          as int);

  @override
  _i4.VideoEvent? getVideoById(String? eventId) =>
      (super.noSuchMethod(Invocation.method(#getVideoById, [eventId]))
          as _i4.VideoEvent?);

  @override
  bool isSubscribed(_i3.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscribed, [type]),
            returnValue: false,
          )
          as bool);

  @override
  List<_i4.VideoEvent> getVideosByAuthor(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getVideosByAuthor, [pubkey]),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  void removeVideoFromAuthorList(String? authorPubkey, String? videoId) =>
      super.noSuchMethod(
        Invocation.method(#removeVideoFromAuthorList, [authorPubkey, videoId]),
        returnValueForMissingStub: null,
      );

  @override
  bool isVideoLocallyDeleted(String? videoId) =>
      (super.noSuchMethod(
            Invocation.method(#isVideoLocallyDeleted, [videoId]),
            returnValue: false,
          )
          as bool);

  @override
  _i10.Future<List<String>> getRepostersForVideo(String? videoId) =>
      (super.noSuchMethod(
            Invocation.method(#getRepostersForVideo, [videoId]),
            returnValue: _i10.Future<List<String>>.value(<String>[]),
          )
          as _i10.Future<List<String>>);

  @override
  _i10.Future<void> subscribeToVideoFeed({
    required _i3.SubscriptionType? subscriptionType,
    List<String>? authors,
    List<String>? hashtags,
    String? group,
    int? since,
    int? until,
    int? limit = 200,
    bool? replace = true,
    bool? includeReposts = false,
    _i11.VideoSortField? sortBy,
    _i11.NIP50SortMode? nip50Sort,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToVideoFeed, [], {
              #subscriptionType: subscriptionType,
              #authors: authors,
              #hashtags: hashtags,
              #group: group,
              #since: since,
              #until: until,
              #limit: limit,
              #replace: replace,
              #includeReposts: includeReposts,
              #sortBy: sortBy,
              #nip50Sort: nip50Sort,
              #force: force,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> subscribeToUserVideos(String? pubkey, {int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToUserVideos,
              [pubkey],
              {#limit: limit},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> queryHistoricalUserVideos(
    String? pubkey, {
    int? until,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryHistoricalUserVideos,
              [pubkey],
              {#until: until, #limit: limit},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> subscribeToHashtagVideos(
    List<String>? hashtags, {
    int? limit = 100,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToHashtagVideos,
              [hashtags],
              {#limit: limit, #force: force},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> subscribeToHomeFeed(
    List<String>? followingPubkeys, {
    int? limit = 100,
    _i11.VideoSortField? sortBy,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToHomeFeed,
              [followingPubkeys],
              {#limit: limit, #sortBy: sortBy, #force: force},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> subscribeToDiscovery({
    int? limit = 100,
    _i11.VideoSortField? sortBy,
    _i11.NIP50SortMode? nip50Sort,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToDiscovery, [], {
              #limit: limit,
              #sortBy: sortBy,
              #nip50Sort: nip50Sort,
              #force: force,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> subscribeToGroupVideos(
    String? group, {
    List<String>? authors,
    int? since,
    int? until,
    int? limit = 200,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToGroupVideos,
              [group],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  List<_i4.VideoEvent> getVideoEventsByGroup(String? group) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByGroup, [group]),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  _i10.Future<void> refreshVideoFeed() =>
      (super.noSuchMethod(
            Invocation.method(#refreshVideoFeed, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loadMoreVideos({int? limit = 100}) =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreVideos, [], {#limit: limit}),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loadMoreEvents(
    _i3.SubscriptionType? subscriptionType, {
    int? limit = 500,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadMoreEvents,
              [subscriptionType],
              {#limit: limit},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void resetPaginationState(_i3.SubscriptionType? subscriptionType) =>
      super.noSuchMethod(
        Invocation.method(#resetPaginationState, [subscriptionType]),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> loadMoreContentUnlimited({
    _i3.SubscriptionType? subscriptionType = _i3.SubscriptionType.discovery,
    int? limit = 300,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreContentUnlimited, [], {
              #subscriptionType: subscriptionType,
              #limit: limit,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i4.VideoEvent? getVideoEventById(String? eventId) =>
      (super.noSuchMethod(Invocation.method(#getVideoEventById, [eventId]))
          as _i4.VideoEvent?);

  @override
  _i4.VideoEvent? getVideoEventByVineId(String? vineId) =>
      (super.noSuchMethod(Invocation.method(#getVideoEventByVineId, [vineId]))
          as _i4.VideoEvent?);

  @override
  _i10.Future<_i4.VideoEvent?> queryVideoByVineId(String? vineId) =>
      (super.noSuchMethod(
            Invocation.method(#queryVideoByVineId, [vineId]),
            returnValue: _i10.Future<_i4.VideoEvent?>.value(),
          )
          as _i10.Future<_i4.VideoEvent?>);

  @override
  List<_i4.VideoEvent> getVideoEventsByAuthor(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByAuthor, [pubkey]),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  List<_i4.VideoEvent> getVideoEventsByHashtags(List<String>? hashtags) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByHashtags, [hashtags]),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  void clearVideoEvents() => super.noSuchMethod(
    Invocation.method(#clearVideoEvents, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> unsubscribeFromVideoFeed() =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromVideoFeed, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  List<_i4.VideoEvent> getVideoEventsByEngagement() =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByEngagement, []),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  List<_i4.VideoEvent> getRecentVideoEvents({int? hours = 24}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentVideoEvents, [], {#hours: hours}),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  Set<String> getUniqueAuthors() =>
      (super.noSuchMethod(
            Invocation.method(#getUniqueAuthors, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Set<String> getAllHashtags() =>
      (super.noSuchMethod(
            Invocation.method(#getAllHashtags, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Map<String, int> getVideoCountByAuthor() =>
      (super.noSuchMethod(
            Invocation.method(#getVideoCountByAuthor, []),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  Map<String, dynamic> getConnectionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectionStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i10.Future<void> retrySubscription() =>
      (super.noSuchMethod(
            Invocation.method(#retrySubscription, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void shuffleForDiscovery() => super.noSuchMethod(
    Invocation.method(#shuffleForDiscovery, []),
    returnValueForMissingStub: null,
  );

  @override
  void addVideoEvent(_i4.VideoEvent? videoEvent) => super.noSuchMethod(
    Invocation.method(#addVideoEvent, [videoEvent]),
    returnValueForMissingStub: null,
  );

  @override
  void updateVideoEvent(_i4.VideoEvent? updatedVideo) => super.noSuchMethod(
    Invocation.method(#updateVideoEvent, [updatedVideo]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> searchVideosByHashtag(String? hashtag) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosByHashtag, [hashtag]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> searchVideosWithFilters({
    required String? query,
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosWithFilters, [], {
              #query: query,
              #authors: authors,
              #since: since,
              #until: until,
              #limit: limit,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void clearSearchResults() => super.noSuchMethod(
    Invocation.method(#clearSearchResults, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i4.VideoEvent> processSearchResults(List<_i9.Event>? events) =>
      (super.noSuchMethod(
            Invocation.method(#processSearchResults, [events]),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  List<_i4.VideoEvent> deduplicateSearchResults(
    List<_i4.VideoEvent>? results,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deduplicateSearchResults, [results]),
            returnValue: <_i4.VideoEvent>[],
          )
          as List<_i4.VideoEvent>);

  @override
  _i10.Future<void> searchVideosWithTimeRange({
    required String? query,
    required DateTime? since,
    required DateTime? until,
    List<String>? authors,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosWithTimeRange, [], {
              #query: query,
              #since: since,
              #until: until,
              #authors: authors,
              #limit: limit,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> searchVideosWithExtensions(String? queryWithExtensions) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosWithExtensions, [
              queryWithExtensions,
            ]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  Map<_i3.SubscriptionType, _i3.PaginationState>
  getPaginationStatesForTesting() =>
      (super.noSuchMethod(
            Invocation.method(#getPaginationStatesForTesting, []),
            returnValue: <_i3.SubscriptionType, _i3.PaginationState>{},
          )
          as Map<_i3.SubscriptionType, _i3.PaginationState>);

  @override
  void addVideoEventForTesting(
    _i4.VideoEvent? event,
    _i3.SubscriptionType? type, {
    required bool? isHistorical,
  }) => super.noSuchMethod(
    Invocation.method(
      #addVideoEventForTesting,
      [event, type],
      {#isHistorical: isHistorical},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void injectTestVideos(List<_i4.VideoEvent>? videos) => super.noSuchMethod(
    Invocation.method(#injectTestVideos, [videos]),
    returnValueForMissingStub: null,
  );

  @override
  void handleEventForTesting(_i9.Event? event, _i3.SubscriptionType? type) =>
      super.noSuchMethod(
        Invocation.method(#handleEventForTesting, [event, type]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NostrClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrClient extends _i1.Mock implements _i2.NostrClient {
  MockNostrClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#publicKey),
            ),
          )
          as String);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  List<String> get configuredRelays =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get connectedRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  int get configuredRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  Map<String, _i2.RelayConnectionStatus> get relayStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatuses),
            returnValue: <String, _i2.RelayConnectionStatus>{},
          )
          as Map<String, _i2.RelayConnectionStatus>);

  @override
  _i10.Stream<Map<String, _i2.RelayConnectionStatus>> get relayStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatusStream),
            returnValue:
                _i10.Stream<Map<String, _i2.RelayConnectionStatus>>.empty(),
          )
          as _i10.Stream<Map<String, _i2.RelayConnectionStatus>>);

  @override
  String get primaryRelay =>
      (super.noSuchMethod(
            Invocation.getter(#primaryRelay),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#primaryRelay),
            ),
          )
          as String);

  @override
  _i10.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i9.Event?> publishEvent(
    _i9.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #publishEvent,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i10.Future<_i9.Event?>.value(),
          )
          as _i10.Future<_i9.Event?>);

  @override
  _i10.Future<List<_i9.Event>> queryEvents(
    List<_i12.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #useGateway: useGateway,
                #useCache: useCache,
              },
            ),
            returnValue: _i10.Future<List<_i9.Event>>.value(<_i9.Event>[]),
          )
          as _i10.Future<List<_i9.Event>>);

  @override
  _i10.Future<_i2.CountResult> countEvents(
    List<_i12.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #countEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #timeout: timeout,
              },
            ),
            returnValue: _i10.Future<_i2.CountResult>.value(
              _FakeCountResult_0(
                this,
                Invocation.method(
                  #countEvents,
                  [filters],
                  {
                    #subscriptionId: subscriptionId,
                    #tempRelays: tempRelays,
                    #relayTypes: relayTypes,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i10.Future<_i2.CountResult>);

  @override
  _i10.Future<_i9.Event?> fetchEventById(
    String? eventId, {
    String? relayUrl,
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEventById,
              [eventId],
              {
                #relayUrl: relayUrl,
                #useGateway: useGateway,
                #useCache: useCache,
              },
            ),
            returnValue: _i10.Future<_i9.Event?>.value(),
          )
          as _i10.Future<_i9.Event?>);

  @override
  _i10.Future<_i9.Event?> fetchProfile(
    String? pubkey, {
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchProfile,
              [pubkey],
              {#useGateway: useGateway, #useCache: useCache},
            ),
            returnValue: _i10.Future<_i9.Event?>.value(),
          )
          as _i10.Future<_i9.Event?>);

  @override
  _i10.Stream<_i9.Event> subscribe(
    List<_i12.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribe,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #onEose: onEose,
              },
            ),
            returnValue: _i10.Stream<_i9.Event>.empty(),
          )
          as _i10.Stream<_i9.Event>);

  @override
  _i10.Future<void> unsubscribe(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [subscriptionId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> closeAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#closeAllSubscriptions, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> addRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#addRelay, [relayUrl]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> removeRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelay, [relayUrl]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<Map<String, dynamic>?> getRelayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStats, []),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<void> retryDisconnectedRelays() =>
      (super.noSuchMethod(
            Invocation.method(#retryDisconnectedRelays, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  Map<String, bool> getRelayStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStatus, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i10.Future<_i9.Event?> sendLike(
    String? eventId, {
    String? content,
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendLike,
              [eventId],
              {
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i10.Future<_i9.Event?>.value(),
          )
          as _i10.Future<_i9.Event?>);

  @override
  _i10.Future<_i9.Event?> sendRepost(
    String? eventId, {
    String? relayAddr,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendRepost,
              [eventId],
              {
                #relayAddr: relayAddr,
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i10.Future<_i9.Event?>.value(),
          )
          as _i10.Future<_i9.Event?>);

  @override
  _i10.Future<_i9.Event?> deleteEvent(
    String? eventId, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvent,
              [eventId],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i10.Future<_i9.Event?>.value(),
          )
          as _i10.Future<_i9.Event?>);

  @override
  _i10.Future<_i9.Event?> deleteEvents(
    List<String>? eventIds, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvents,
              [eventIds],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i10.Future<_i9.Event?>.value(),
          )
          as _i10.Future<_i9.Event?>);

  @override
  _i10.Future<_i9.Event?> sendContactList(
    _i13.ContactList? contacts,
    String? content, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendContactList,
              [contacts, content],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i10.Future<_i9.Event?>.value(),
          )
          as _i10.Future<_i9.Event?>);

  @override
  _i10.Stream<_i9.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i10.Stream<_i9.Event>.empty(),
          )
          as _i10.Stream<_i9.Event>);

  @override
  _i10.Stream<_i9.Event> searchUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i10.Stream<_i9.Event>.empty(),
          )
          as _i10.Stream<_i9.Event>);

  @override
  _i10.Future<_i2.NostrBroadcastResult> broadcast(
    _i9.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #broadcast,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i10.Future<_i2.NostrBroadcastResult>.value(
              _FakeNostrBroadcastResult_1(
                this,
                Invocation.method(
                  #broadcast,
                  [event],
                  {#targetRelays: targetRelays},
                ),
              ),
            ),
          )
          as _i10.Future<_i2.NostrBroadcastResult>);

  @override
  _i10.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}
