# ABOUTME: Codemagic CI/CD configuration for diVine mobile app builds.
# ABOUTME: Configured for iOS and Android builds with manual triggering only.

# Steps to setup:
# 1 - Create the Codemagic project with access to the repository.
# 2 - Setup iOS publishing:
#   2.1 - https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app/#:~:text=Creating%20the%20App%20Store%20Connect%20API%20key
# 3 - Setup Android publishing:
#   3.1 - Code signing: https://docs.codemagic.io/yaml-quick-start/building-a-flutter-app/#:~:text=Generating%20a%20keystore
#   3.2 - Connect to Google Play: https://docs.codemagic.io/yaml-publishing/google-play/
# 4 - Setup emails to receive build notifications.
# 5 - Create environment variable group "zendesk_credentials" with:
#   - ZENDESK_APP_ID
#   - ZENDESK_CLIENT_ID
#   - ZENDESK_URL

definitions:
  environment:
    emails: &emails
      - TODO
  scripts:
    - &setup_code_signing_xcode
      name: Set up code signing settings on Xcode project
      script: xcode-project use-profiles
    - &install_flutterfire
      name: Install FlutterFire CLI
      script: dart pub global activate flutterfire_cli
    - &flutter_pub_get
      name: Get Flutter dependencies
      script: flutter pub get
    - &pod_install
      name: Run pod install
      script: find . -name "Podfile" -execdir pod install \;
    - &setup_local_properties
      name: Set up local.properties
      script: echo "flutter.sdk=$FLUTTER_ROOT" > "$CM_BUILD_DIR/mobile/android/local.properties"
    - &build_apk
      name: Build Android APK
      script: |
        flutter build apk --release --build-number=$PROJECT_BUILD_NUMBER \
          --dart-define=ZENDESK_APP_ID=$ZENDESK_APP_ID \
          --dart-define=ZENDESK_CLIENT_ID=$ZENDESK_CLIENT_ID \
          --dart-define=ZENDESK_URL=$ZENDESK_URL
    - &build_aab
      name: Build Android AAB
      script: |
        flutter build appbundle --release --build-number=$PROJECT_BUILD_NUMBER \
          --dart-define=ZENDESK_APP_ID=$ZENDESK_APP_ID \
          --dart-define=ZENDESK_CLIENT_ID=$ZENDESK_CLIENT_ID \
          --dart-define=ZENDESK_URL=$ZENDESK_URL
    - &build_ios
      name: Build and sign iOS
      script: |
        # Offset to continue from existing manual builds (last was 132)
        BUILD_NUMBER=$((PROJECT_BUILD_NUMBER + 132))
        flutter build ipa --release --build-number=$BUILD_NUMBER \
          --dart-define=ZENDESK_APP_ID=$ZENDESK_APP_ID \
          --dart-define=ZENDESK_CLIENT_ID=$ZENDESK_CLIENT_ID \
          --dart-define=ZENDESK_URL=$ZENDESK_URL \
          --export-options-plist=/Users/builder/export_options.plist
    - &build_ios_simulator
      name: Build iOS Simulator app
      script: |
        flutter build ios --simulator \
          --dart-define=ZENDESK_APP_ID=$ZENDESK_APP_ID \
          --dart-define=ZENDESK_CLIENT_ID=$ZENDESK_CLIENT_ID \
          --dart-define=ZENDESK_URL=$ZENDESK_URL
workflows:
  ios-build:
    name: iOS Build
    working_directory: mobile
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: API key for Codemagic # Setup in Codemagic UI
    environment:
      flutter: 3.38.3
      xcode: latest
      cocoapods: default
      groups:
        - zendesk_credentials
      vars:
        BUNDLE_ID: co.openvine.app
      ios_signing:
        distribution_type: app_store
        bundle_identifier: $BUNDLE_ID
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
    triggering:
      events: []
    scripts:
      - *setup_code_signing_xcode
      - *install_flutterfire
      - *pod_install
      - *build_ios
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
        # Don't auto-distribute to any groups - we'll manually add builds to external testers
        beta_groups: []

  ios-simulator-build:
    name: iOS Simulator Build
    working_directory: mobile
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.38.3
      xcode: 16.1  # Pinned to avoid FFmpeg Kit linker issues with newer Xcode
      cocoapods: default
      groups:
        - zendesk_credentials
    cache:
      cache_paths:
        - $HOME/Library/Caches/CocoaPods
        - $HOME/.pub-cache
    triggering:
      events: []
    scripts:
      - *install_flutterfire
      - *flutter_pub_get
      - *pod_install
      - *build_ios_simulator
    artifacts:
      - build/ios/iphonesimulator/Runner.app
      - /tmp/xcodebuild_logs/*.log

  android-build:
    name: Android Build
    working_directory: mobile
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: 3.38.3
      java: 17
      groups:
        - zendesk_credentials
        - google_play_credentials
      android_signing:
        - divine_keystore
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.pub-cache
    triggering:
      events: []
    scripts:
      - *setup_local_properties
      - *build_apk
      - *build_aab
    artifacts:
      - build/app/outputs/apk/release/*.apk
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/mapping/**/mapping.txt
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
