// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/unit/providers/comments_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:nostr_client/nostr_client.dart' as _i3;
import 'package:nostr_sdk/event.dart' as _i6;
import 'package:nostr_sdk/filter.dart' as _i10;
import 'package:nostr_sdk/nostr_sdk.dart' as _i11;
import 'package:openvine/models/video_event.dart' as _i7;
import 'package:openvine/services/auth_service.dart' as _i2;
import 'package:openvine/services/social_service.dart' as _i4;
import 'package:openvine/services/subscription_manager.dart' as _i12;
import 'package:openvine/services/user_profile_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCountResult_1 extends _i1.SmartFake implements _i3.CountResult {
  _FakeCountResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrBroadcastResult_2 extends _i1.SmartFake
    implements _i3.NostrBroadcastResult {
  _FakeNostrBroadcastResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SocialService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialService extends _i1.Mock implements _i4.SocialService {
  MockSocialService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> get likedEventIds =>
      (super.noSuchMethod(
            Invocation.getter(#likedEventIds),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  List<String> get followingPubkeys =>
      (super.noSuchMethod(
            Invocation.getter(#followingPubkeys),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<_i4.FollowSet> get followSets =>
      (super.noSuchMethod(
            Invocation.getter(#followSets),
            returnValue: <_i4.FollowSet>[],
          )
          as List<_i4.FollowSet>);

  @override
  bool isLiked(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#isLiked, [eventId]),
            returnValue: false,
          )
          as bool);

  @override
  bool hasReposted(String? eventId, {String? pubkey, String? dTag}) =>
      (super.noSuchMethod(
            Invocation.method(
              #hasReposted,
              [eventId],
              {#pubkey: pubkey, #dTag: dTag},
            ),
            returnValue: false,
          )
          as bool);

  @override
  int? getCachedLikeCount(String? eventId) =>
      (super.noSuchMethod(Invocation.method(#getCachedLikeCount, [eventId]))
          as int?);

  @override
  bool isFollowing(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#isFollowing, [pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, int>? getCachedFollowerStats(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(#getCachedFollowerStats, [pubkey]))
          as Map<String, int>?);

  @override
  _i4.FollowSet? getFollowSetById(String? setId) =>
      (super.noSuchMethod(Invocation.method(#getFollowSetById, [setId]))
          as _i4.FollowSet?);

  @override
  bool isInFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#isInFollowSet, [setId, pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> toggleLike(String? eventId, String? authorPubkey) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [eventId, authorPubkey]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, dynamic>> getLikeStatus(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getLikeStatus, [eventId]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<List<_i6.Event>> fetchLikedEvents(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLikedEvents, [pubkey]),
            returnValue: _i5.Future<List<_i6.Event>>.value(<_i6.Event>[]),
          )
          as _i5.Future<List<_i6.Event>>);

  @override
  _i5.Future<void> fetchCurrentUserFollowList() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCurrentUserFollowList, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> followUser(String? pubkeyToFollow) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [pubkeyToFollow]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> unfollowUser(String? pubkeyToUnfollow) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [pubkeyToUnfollow]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<Map<String, int>> getFollowerStats(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowerStats, [pubkey]),
            returnValue: _i5.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i5.Future<Map<String, int>>);

  @override
  _i5.Future<_i4.FollowSet?> createFollowSet({
    required String? name,
    String? description,
    String? imageUrl,
    List<String>? initialPubkeys = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createFollowSet, [], {
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #initialPubkeys: initialPubkeys,
            }),
            returnValue: _i5.Future<_i4.FollowSet?>.value(),
          )
          as _i5.Future<_i4.FollowSet?>);

  @override
  _i5.Future<bool> addToFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#addToFollowSet, [setId, pubkey]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeFromFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromFollowSet, [setId, pubkey]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateFollowSet({
    required String? setId,
    String? name,
    String? description,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateFollowSet, [], {
              #setId: setId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteFollowSet(String? setId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFollowSet, [setId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<int> getUserVideoCount(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getUserVideoCount, [pubkey]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> getUserTotalLikes(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTotalLikes, [pubkey]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> postComment({
    required String? content,
    required String? rootEventId,
    required String? rootEventAuthorPubkey,
    String? replyToEventId,
    String? replyToAuthorPubkey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postComment, [], {
              #content: content,
              #rootEventId: rootEventId,
              #rootEventAuthorPubkey: rootEventAuthorPubkey,
              #replyToEventId: replyToEventId,
              #replyToAuthorPubkey: replyToAuthorPubkey,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i6.Event> fetchCommentsForEvent(String? rootEventId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCommentsForEvent, [rootEventId]),
            returnValue: _i5.Stream<_i6.Event>.empty(),
          )
          as _i5.Stream<_i6.Event>);

  @override
  _i5.Future<int> getCommentCount(String? rootEventId) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentCount, [rootEventId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<void> cancelCommentSubscriptions(String? rootEventId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelCommentSubscriptions, [rootEventId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleRepost(_i7.VideoEvent? videoToRepost) =>
      (super.noSuchMethod(
            Invocation.method(#toggleRepost, [videoToRepost]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> repostEvent(_i6.Event? eventToRepost) =>
      (super.noSuchMethod(
            Invocation.method(#repostEvent, [eventToRepost]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> publishRightToBeForgotten() =>
      (super.noSuchMethod(
            Invocation.method(#publishRightToBeForgotten, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _i2.AuthState.unauthenticated,
          )
          as _i2.AuthState);

  @override
  _i5.Stream<_i2.AuthState> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i5.Stream<_i2.AuthState>.empty(),
          )
          as _i5.Stream<_i2.AuthState>);

  @override
  _i5.Stream<_i2.UserProfile?> get profileStream =>
      (super.noSuchMethod(
            Invocation.getter(#profileStream),
            returnValue: _i5.Stream<_i2.UserProfile?>.empty(),
          )
          as _i5.Stream<_i2.UserProfile?>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> get userStats =>
      (super.noSuchMethod(
            Invocation.getter(#userStats),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.AuthResult> createNewIdentity({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#createNewIdentity, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i5.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#createNewIdentity, [], {
                  #biometricPrompt: biometricPrompt,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<_i2.AuthResult> importFromNsec(
    String? nsec, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromNsec,
              [nsec],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i5.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromNsec,
                  [nsec],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<_i2.AuthResult> importFromHex(
    String? privateKeyHex, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromHex,
              [privateKeyHex],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i5.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromHex,
                  [privateKeyHex],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<void> refreshCurrentProfile(
    _i8.UserProfileService? userProfileService,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentProfile, [userProfileService]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> acceptTermsOfService() =>
      (super.noSuchMethod(
            Invocation.method(#acceptTermsOfService, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signOut({bool? deleteKeys = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#deleteKeys: deleteKeys}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getPrivateKeyForSigning({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateKeyForSigning, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> exportNsec({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#exportNsec, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<_i6.Event?> createAndSignEvent({
    required int? kind,
    required String? content,
    List<List<String>>? tags,
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAndSignEvent, [], {
              #kind: kind,
              #content: content,
              #tags: tags,
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NostrClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrClient extends _i1.Mock implements _i3.NostrClient {
  MockNostrClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#publicKey),
            ),
          )
          as String);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  List<String> get configuredRelays =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get connectedRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  int get configuredRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  Map<String, _i3.RelayConnectionStatus> get relayStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatuses),
            returnValue: <String, _i3.RelayConnectionStatus>{},
          )
          as Map<String, _i3.RelayConnectionStatus>);

  @override
  _i5.Stream<Map<String, _i3.RelayConnectionStatus>> get relayStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatusStream),
            returnValue:
                _i5.Stream<Map<String, _i3.RelayConnectionStatus>>.empty(),
          )
          as _i5.Stream<Map<String, _i3.RelayConnectionStatus>>);

  @override
  String get primaryRelay =>
      (super.noSuchMethod(
            Invocation.getter(#primaryRelay),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#primaryRelay),
            ),
          )
          as String);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.Event?> publishEvent(
    _i6.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #publishEvent,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Future<List<_i6.Event>> queryEvents(
    List<_i10.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #useGateway: useGateway,
                #useCache: useCache,
              },
            ),
            returnValue: _i5.Future<List<_i6.Event>>.value(<_i6.Event>[]),
          )
          as _i5.Future<List<_i6.Event>>);

  @override
  _i5.Future<_i3.CountResult> countEvents(
    List<_i10.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #countEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #timeout: timeout,
              },
            ),
            returnValue: _i5.Future<_i3.CountResult>.value(
              _FakeCountResult_1(
                this,
                Invocation.method(
                  #countEvents,
                  [filters],
                  {
                    #subscriptionId: subscriptionId,
                    #tempRelays: tempRelays,
                    #relayTypes: relayTypes,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.CountResult>);

  @override
  _i5.Future<_i6.Event?> fetchEventById(
    String? eventId, {
    String? relayUrl,
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEventById,
              [eventId],
              {
                #relayUrl: relayUrl,
                #useGateway: useGateway,
                #useCache: useCache,
              },
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Future<_i6.Event?> fetchProfile(
    String? pubkey, {
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchProfile,
              [pubkey],
              {#useGateway: useGateway, #useCache: useCache},
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Stream<_i6.Event> subscribe(
    List<_i10.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribe,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #onEose: onEose,
              },
            ),
            returnValue: _i5.Stream<_i6.Event>.empty(),
          )
          as _i5.Stream<_i6.Event>);

  @override
  _i5.Future<void> unsubscribe(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [subscriptionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> closeAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#closeAllSubscriptions, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> addRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#addRelay, [relayUrl]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelay, [relayUrl]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>?> getRelayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStats, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> retryDisconnectedRelays() =>
      (super.noSuchMethod(
            Invocation.method(#retryDisconnectedRelays, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<String, bool> getRelayStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStatus, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i5.Future<_i6.Event?> sendLike(
    String? eventId, {
    String? content,
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendLike,
              [eventId],
              {
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Future<_i6.Event?> sendRepost(
    String? eventId, {
    String? relayAddr,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendRepost,
              [eventId],
              {
                #relayAddr: relayAddr,
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Future<_i6.Event?> deleteEvent(
    String? eventId, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvent,
              [eventId],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Future<_i6.Event?> deleteEvents(
    List<String>? eventIds, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvents,
              [eventIds],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Future<_i6.Event?> sendContactList(
    _i11.ContactList? contacts,
    String? content, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendContactList,
              [contacts, content],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Stream<_i6.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i5.Stream<_i6.Event>.empty(),
          )
          as _i5.Stream<_i6.Event>);

  @override
  _i5.Stream<_i6.Event> searchUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i5.Stream<_i6.Event>.empty(),
          )
          as _i5.Stream<_i6.Event>);

  @override
  _i5.Future<_i3.NostrBroadcastResult> broadcast(
    _i6.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #broadcast,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i3.NostrBroadcastResult>.value(
              _FakeNostrBroadcastResult_2(
                this,
                Invocation.method(
                  #broadcast,
                  [event],
                  {#targetRelays: targetRelays},
                ),
              ),
            ),
          )
          as _i5.Future<_i3.NostrBroadcastResult>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SubscriptionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionManager extends _i1.Mock
    implements _i12.SubscriptionManager {
  MockSubscriptionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get activeSubscriptionIds =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptionIds),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get activeSubscriptionCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptionCount),
            returnValue: 0,
          )
          as int);

  @override
  void setCacheLookup({
    _i6.Event? Function(String)? getCachedEvent,
    bool Function(String)? hasProfileCached,
  }) => super.noSuchMethod(
    Invocation.method(#setCacheLookup, [], {
      #getCachedEvent: getCachedEvent,
      #hasProfileCached: hasProfileCached,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<String> createSubscription({
    required String? name,
    required List<_i10.Filter>? filters,
    required dynamic Function(_i6.Event)? onEvent,
    dynamic Function(dynamic)? onError,
    dynamic Function()? onComplete,
    Duration? timeout,
    int? priority = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSubscription, [], {
              #name: name,
              #filters: filters,
              #onEvent: onEvent,
              #onError: onError,
              #onComplete: onComplete,
              #timeout: timeout,
              #priority: priority,
            }),
            returnValue: _i5.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#createSubscription, [], {
                  #name: name,
                  #filters: filters,
                  #onEvent: onEvent,
                  #onError: onError,
                  #onComplete: onComplete,
                  #timeout: timeout,
                  #priority: priority,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> cancelSubscription(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscription, [subscriptionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllSubscriptions, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isSubscriptionActive(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscriptionActive, [subscriptionId]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> cancelSubscriptionsByName(String? namePattern) =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscriptionsByName, [namePattern]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
