// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/services/upload_manager_cancel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;

import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:openvine/services/auth_service.dart' as _i2;
import 'package:openvine/services/blossom_upload_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthService_0 extends _i1.SmartFake implements _i2.AuthService {
  _FakeAuthService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBlossomUploadResult_2 extends _i1.SmartFake
    implements _i4.BlossomUploadResult {
  _FakeBlossomUploadResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BlossomUploadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlossomUploadService extends _i1.Mock
    implements _i4.BlossomUploadService {
  MockBlossomUploadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_0(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i2.AuthService);

  @override
  _i3.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_1(this, Invocation.getter(#dio)),
          )
          as _i3.Dio);

  @override
  _i5.Future<String?> getBlossomServer() =>
      (super.noSuchMethod(
            Invocation.method(#getBlossomServer, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> setBlossomServer(String? serverUrl) =>
      (super.noSuchMethod(
            Invocation.method(#setBlossomServer, [serverUrl]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isBlossomEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isBlossomEnabled, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> setBlossomEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setBlossomEnabled, [enabled]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i4.BlossomUploadResult> uploadVideo({
    required _i6.File? videoFile,
    required String? nostrPubkey,
    required String? title,
    String? description,
    List<String>? hashtags,
    String? proofManifestJson,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadVideo, [], {
              #videoFile: videoFile,
              #nostrPubkey: nostrPubkey,
              #title: title,
              #description: description,
              #hashtags: hashtags,
              #proofManifestJson: proofManifestJson,
              #onProgress: onProgress,
            }),
            returnValue: _i5.Future<_i4.BlossomUploadResult>.value(
              _FakeBlossomUploadResult_2(
                this,
                Invocation.method(#uploadVideo, [], {
                  #videoFile: videoFile,
                  #nostrPubkey: nostrPubkey,
                  #title: title,
                  #description: description,
                  #hashtags: hashtags,
                  #proofManifestJson: proofManifestJson,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i4.BlossomUploadResult>);

  @override
  _i5.Future<_i4.BlossomUploadResult> uploadImage({
    required _i6.File? imageFile,
    required String? nostrPubkey,
    String? mimeType = 'image/jpeg',
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [], {
              #imageFile: imageFile,
              #nostrPubkey: nostrPubkey,
              #mimeType: mimeType,
              #onProgress: onProgress,
            }),
            returnValue: _i5.Future<_i4.BlossomUploadResult>.value(
              _FakeBlossomUploadResult_2(
                this,
                Invocation.method(#uploadImage, [], {
                  #imageFile: imageFile,
                  #nostrPubkey: nostrPubkey,
                  #mimeType: mimeType,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i5.Future<_i4.BlossomUploadResult>);

  @override
  _i5.Future<String?> uploadBugReport({
    required _i6.File? bugReportFile,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadBugReport, [], {
              #bugReportFile: bugReportFile,
              #onProgress: onProgress,
            }),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);
}
