// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/services/video_event_service_sorted_queries_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i15;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:nostr_sdk/event.dart' as _i8;
import 'package:nostr_sdk/filter.dart' as _i9;
import 'package:openvine/database/app_database.dart' as _i4;
import 'package:openvine/models/nip94_metadata.dart' as _i10;
import 'package:openvine/models/user_profile.dart' as _i13;
import 'package:openvine/services/event_router.dart' as _i16;
import 'package:openvine/services/nostr_key_manager.dart' as _i2;
import 'package:openvine/services/nostr_service_interface.dart' as _i3;
import 'package:openvine/services/profile_cache_service.dart' as _i14;
import 'package:openvine/services/relay_capability_service.dart' as _i5;
import 'package:openvine/services/subscription_manager.dart' as _i11;
import 'package:openvine/services/user_profile_service.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNostrKeyManager_0 extends _i1.SmartFake
    implements _i2.NostrKeyManager {
  _FakeNostrKeyManager_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrBroadcastResult_1 extends _i1.SmartFake
    implements _i3.NostrBroadcastResult {
  _FakeNostrBroadcastResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppDatabase_2 extends _i1.SmartFake implements _i4.AppDatabase {
  _FakeAppDatabase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRelayCapabilities_3 extends _i1.SmartFake
    implements _i5.RelayCapabilities {
  _FakeRelayCapabilities_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [INostrService].
///
/// See the documentation for Mockito's code generation for more information.
class MockINostrService extends _i1.Mock implements _i3.INostrService {
  MockINostrService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  _i2.NostrKeyManager get keyManager =>
      (super.noSuchMethod(
            Invocation.getter(#keyManager),
            returnValue: _FakeNostrKeyManager_0(
              this,
              Invocation.getter(#keyManager),
            ),
          )
          as _i2.NostrKeyManager);

  @override
  int get relayCount =>
      (super.noSuchMethod(Invocation.getter(#relayCount), returnValue: 0)
          as int);

  @override
  int get connectedRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  List<String> get relays =>
      (super.noSuchMethod(Invocation.getter(#relays), returnValue: <String>[])
          as List<String>);

  @override
  Map<String, dynamic> get relayStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatuses),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, bool> get relayAuthStates =>
      (super.noSuchMethod(
            Invocation.getter(#relayAuthStates),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i6.Stream<Map<String, bool>> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i6.Stream<Map<String, bool>>.empty(),
          )
          as _i6.Stream<Map<String, bool>>);

  @override
  bool get isVineRelayAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isVineRelayAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  String get primaryRelay =>
      (super.noSuchMethod(
            Invocation.getter(#primaryRelay),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#primaryRelay),
            ),
          )
          as String);

  @override
  bool isRelayAuthenticated(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#isRelayAuthenticated, [relayUrl]),
            returnValue: false,
          )
          as bool);

  @override
  void setAuthTimeout(Duration? timeout) => super.noSuchMethod(
    Invocation.method(#setAuthTimeout, [timeout]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> initialize({List<String>? customRelays}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {#customRelays: customRelays}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Stream<_i8.Event> subscribeToEvents({
    required List<_i9.Filter>? filters,
    bool? bypassLimits = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToEvents, [], {
              #filters: filters,
              #bypassLimits: bypassLimits,
              #onEose: onEose,
            }),
            returnValue: _i6.Stream<_i8.Event>.empty(),
          )
          as _i6.Stream<_i8.Event>);

  @override
  _i6.Future<_i3.NostrBroadcastResult> broadcastEvent(_i8.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastEvent, [event]),
            returnValue: _i6.Future<_i3.NostrBroadcastResult>.value(
              _FakeNostrBroadcastResult_1(
                this,
                Invocation.method(#broadcastEvent, [event]),
              ),
            ),
          )
          as _i6.Future<_i3.NostrBroadcastResult>);

  @override
  _i6.Future<_i3.NostrBroadcastResult> publishFileMetadata({
    required _i10.NIP94Metadata? metadata,
    required String? content,
    List<String>? hashtags = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#publishFileMetadata, [], {
              #metadata: metadata,
              #content: content,
              #hashtags: hashtags,
            }),
            returnValue: _i6.Future<_i3.NostrBroadcastResult>.value(
              _FakeNostrBroadcastResult_1(
                this,
                Invocation.method(#publishFileMetadata, [], {
                  #metadata: metadata,
                  #content: content,
                  #hashtags: hashtags,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.NostrBroadcastResult>);

  @override
  _i6.Future<bool> addRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#addRelay, [relayUrl]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> removeRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelay, [relayUrl]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  Map<String, bool> getRelayStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStatus, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i6.Future<void> reconnectAll() =>
      (super.noSuchMethod(
            Invocation.method(#reconnectAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> retryInitialization() =>
      (super.noSuchMethod(
            Invocation.method(#retryInitialization, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> closeAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#closeAllSubscriptions, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.Event>> getEvents({
    required List<_i9.Filter>? filters,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, [], {
              #filters: filters,
              #limit: limit,
            }),
            returnValue: _i6.Future<List<_i8.Event>>.value(<_i8.Event>[]),
          )
          as _i6.Future<List<_i8.Event>>);

  @override
  _i6.Future<_i8.Event?> fetchEventById(String? eventId, {String? relayUrl}) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEventById,
              [eventId],
              {#relayUrl: relayUrl},
            ),
            returnValue: _i6.Future<_i8.Event?>.value(),
          )
          as _i6.Future<_i8.Event?>);

  @override
  _i6.Stream<_i8.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i6.Stream<_i8.Event>.empty(),
          )
          as _i6.Stream<_i8.Event>);

  @override
  _i6.Future<Map<String, dynamic>?> getRelayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStats, []),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [SubscriptionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionManager extends _i1.Mock
    implements _i11.SubscriptionManager {
  MockSubscriptionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get activeSubscriptionIds =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptionIds),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get activeSubscriptionCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptionCount),
            returnValue: 0,
          )
          as int);

  @override
  void setCacheLookup({
    _i8.Event? Function(String)? getCachedEvent,
    bool Function(String)? hasProfileCached,
  }) => super.noSuchMethod(
    Invocation.method(#setCacheLookup, [], {
      #getCachedEvent: getCachedEvent,
      #hasProfileCached: hasProfileCached,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<String> createSubscription({
    required String? name,
    required List<_i9.Filter>? filters,
    required dynamic Function(_i8.Event)? onEvent,
    dynamic Function(dynamic)? onError,
    dynamic Function()? onComplete,
    Duration? timeout,
    int? priority = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSubscription, [], {
              #name: name,
              #filters: filters,
              #onEvent: onEvent,
              #onError: onError,
              #onComplete: onComplete,
              #timeout: timeout,
              #priority: priority,
            }),
            returnValue: _i6.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#createSubscription, [], {
                  #name: name,
                  #filters: filters,
                  #onEvent: onEvent,
                  #onError: onError,
                  #onComplete: onComplete,
                  #timeout: timeout,
                  #priority: priority,
                }),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> cancelSubscription(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscription, [subscriptionId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> cancelAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllSubscriptions, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  bool isSubscriptionActive(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscriptionActive, [subscriptionId]),
            returnValue: false,
          )
          as bool);

  @override
  _i6.Future<void> cancelSubscriptionsByName(String? namePattern) =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscriptionsByName, [namePattern]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i12.UserProfileService {
  MockUserProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i13.UserProfile> get allProfiles =>
      (super.noSuchMethod(
            Invocation.getter(#allProfiles),
            returnValue: <String, _i13.UserProfile>{},
          )
          as Map<String, _i13.UserProfile>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setPersistentCache(_i14.ProfileCacheService? cacheService) =>
      super.noSuchMethod(
        Invocation.method(#setPersistentCache, [cacheService]),
        returnValueForMissingStub: null,
      );

  @override
  _i13.UserProfile? getCachedProfile(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(#getCachedProfile, [pubkey]))
          as _i13.UserProfile?);

  @override
  bool hasProfile(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#hasProfile, [pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  bool shouldSkipProfileFetch(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#shouldSkipProfileFetch, [pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  void markProfileAsMissing(String? pubkey) => super.noSuchMethod(
    Invocation.method(#markProfileAsMissing, [pubkey]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> updateCachedProfile(_i13.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateCachedProfile, [profile]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i13.UserProfile?> fetchProfile(
    String? pubkey, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchProfile,
              [pubkey],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i6.Future<_i13.UserProfile?>.value(),
          )
          as _i6.Future<_i13.UserProfile?>);

  @override
  _i6.Future<void> prefetchProfilesImmediately(List<String>? pubkeys) =>
      (super.noSuchMethod(
            Invocation.method(#prefetchProfilesImmediately, [pubkeys]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> fetchMultipleProfiles(
    List<String>? pubkeys, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchMultipleProfiles,
              [pubkeys],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  String getDisplayName(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getDisplayName, [pubkey]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#getDisplayName, [pubkey]),
            ),
          )
          as String);

  @override
  String? getAvatarUrl(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(#getAvatarUrl, [pubkey]))
          as String?);

  @override
  String? getUserBio(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(#getUserBio, [pubkey])) as String?);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeProfile(String? pubkey) => super.noSuchMethod(
    Invocation.method(#removeProfile, [pubkey]),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void handleProfileEventForTesting(_i8.Event? event) => super.noSuchMethod(
    Invocation.method(#handleProfileEventForTesting, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i15.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [EventRouter].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRouter extends _i1.Mock implements _i16.EventRouter {
  MockEventRouter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AppDatabase get db =>
      (super.noSuchMethod(
            Invocation.getter(#db),
            returnValue: _FakeAppDatabase_2(this, Invocation.getter(#db)),
          )
          as _i4.AppDatabase);

  @override
  _i6.Future<void> handleEvent(_i8.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#handleEvent, [event]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [RelayCapabilityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelayCapabilityService extends _i1.Mock
    implements _i5.RelayCapabilityService {
  MockRelayCapabilityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i5.RelayCapabilities> getRelayCapabilities(String? relayWsUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getRelayCapabilities, [relayWsUrl]),
            returnValue: _i6.Future<_i5.RelayCapabilities>.value(
              _FakeRelayCapabilities_3(
                this,
                Invocation.method(#getRelayCapabilities, [relayWsUrl]),
              ),
            ),
          )
          as _i6.Future<_i5.RelayCapabilities>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
