// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/services/video_event_service_pagination_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:nostr_client/nostr_client.dart' as _i3;
import 'package:nostr_client/src/models/models.dart' as _i2;
import 'package:nostr_sdk/nostr_sdk.dart' as _i6;
import 'package:openvine/services/subscription_manager.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCountResult_0 extends _i1.SmartFake implements _i2.CountResult {
  _FakeCountResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrBroadcastResult_1 extends _i1.SmartFake
    implements _i2.NostrBroadcastResult {
  _FakeNostrBroadcastResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NostrClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrClient extends _i1.Mock implements _i3.NostrClient {
  MockNostrClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#publicKey),
            ),
          )
          as String);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  List<String> get configuredRelays =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get connectedRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  int get configuredRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  Map<String, _i2.RelayConnectionStatus> get relayStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatuses),
            returnValue: <String, _i2.RelayConnectionStatus>{},
          )
          as Map<String, _i2.RelayConnectionStatus>);

  @override
  _i5.Stream<Map<String, _i2.RelayConnectionStatus>> get relayStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatusStream),
            returnValue:
                _i5.Stream<Map<String, _i2.RelayConnectionStatus>>.empty(),
          )
          as _i5.Stream<Map<String, _i2.RelayConnectionStatus>>);

  @override
  String get primaryRelay =>
      (super.noSuchMethod(
            Invocation.getter(#primaryRelay),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#primaryRelay),
            ),
          )
          as String);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.Event?> publishEvent(
    _i6.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #publishEvent,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Future<List<_i6.Event>> queryEvents(
    List<_i6.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #useGateway: useGateway,
                #useCache: useCache,
              },
            ),
            returnValue: _i5.Future<List<_i6.Event>>.value(<_i6.Event>[]),
          )
          as _i5.Future<List<_i6.Event>>);

  @override
  _i5.Future<_i2.CountResult> countEvents(
    List<_i6.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #countEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #timeout: timeout,
              },
            ),
            returnValue: _i5.Future<_i2.CountResult>.value(
              _FakeCountResult_0(
                this,
                Invocation.method(
                  #countEvents,
                  [filters],
                  {
                    #subscriptionId: subscriptionId,
                    #tempRelays: tempRelays,
                    #relayTypes: relayTypes,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.CountResult>);

  @override
  _i5.Future<_i6.Event?> fetchEventById(
    String? eventId, {
    String? relayUrl,
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEventById,
              [eventId],
              {
                #relayUrl: relayUrl,
                #useGateway: useGateway,
                #useCache: useCache,
              },
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Future<_i6.Event?> fetchProfile(
    String? pubkey, {
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchProfile,
              [pubkey],
              {#useGateway: useGateway, #useCache: useCache},
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Stream<_i6.Event> subscribe(
    List<_i6.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribe,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #onEose: onEose,
              },
            ),
            returnValue: _i5.Stream<_i6.Event>.empty(),
          )
          as _i5.Stream<_i6.Event>);

  @override
  _i5.Future<void> unsubscribe(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [subscriptionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> closeAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#closeAllSubscriptions, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> addRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#addRelay, [relayUrl]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelay, [relayUrl]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>?> getRelayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStats, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> retryDisconnectedRelays() =>
      (super.noSuchMethod(
            Invocation.method(#retryDisconnectedRelays, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<String, bool> getRelayStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStatus, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i5.Future<_i6.Event?> sendLike(
    String? eventId, {
    String? content,
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendLike,
              [eventId],
              {
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Future<_i6.Event?> sendRepost(
    String? eventId, {
    String? relayAddr,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendRepost,
              [eventId],
              {
                #relayAddr: relayAddr,
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Future<_i6.Event?> deleteEvent(
    String? eventId, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvent,
              [eventId],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Future<_i6.Event?> deleteEvents(
    List<String>? eventIds, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvents,
              [eventIds],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Future<_i6.Event?> sendContactList(
    _i6.ContactList? contacts,
    String? content, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendContactList,
              [contacts, content],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i6.Event?>.value(),
          )
          as _i5.Future<_i6.Event?>);

  @override
  _i5.Stream<_i6.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i5.Stream<_i6.Event>.empty(),
          )
          as _i5.Stream<_i6.Event>);

  @override
  _i5.Stream<_i6.Event> searchUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i5.Stream<_i6.Event>.empty(),
          )
          as _i5.Stream<_i6.Event>);

  @override
  _i5.Future<_i2.NostrBroadcastResult> broadcast(
    _i6.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #broadcast,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i2.NostrBroadcastResult>.value(
              _FakeNostrBroadcastResult_1(
                this,
                Invocation.method(
                  #broadcast,
                  [event],
                  {#targetRelays: targetRelays},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.NostrBroadcastResult>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SubscriptionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionManager extends _i1.Mock
    implements _i7.SubscriptionManager {
  MockSubscriptionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get activeSubscriptionIds =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptionIds),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get activeSubscriptionCount =>
      (super.noSuchMethod(
            Invocation.getter(#activeSubscriptionCount),
            returnValue: 0,
          )
          as int);

  @override
  void setCacheLookup({
    _i6.Event? Function(String)? getCachedEvent,
    bool Function(String)? hasProfileCached,
  }) => super.noSuchMethod(
    Invocation.method(#setCacheLookup, [], {
      #getCachedEvent: getCachedEvent,
      #hasProfileCached: hasProfileCached,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<String> createSubscription({
    required String? name,
    required List<_i6.Filter>? filters,
    required dynamic Function(_i6.Event)? onEvent,
    dynamic Function(dynamic)? onError,
    dynamic Function()? onComplete,
    Duration? timeout,
    int? priority = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSubscription, [], {
              #name: name,
              #filters: filters,
              #onEvent: onEvent,
              #onError: onError,
              #onComplete: onComplete,
              #timeout: timeout,
              #priority: priority,
            }),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#createSubscription, [], {
                  #name: name,
                  #filters: filters,
                  #onEvent: onEvent,
                  #onError: onError,
                  #onComplete: onComplete,
                  #timeout: timeout,
                  #priority: priority,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> cancelSubscription(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscription, [subscriptionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cancelAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllSubscriptions, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool isSubscriptionActive(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscriptionActive, [subscriptionId]),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> cancelSubscriptionsByName(String? namePattern) =>
      (super.noSuchMethod(
            Invocation.method(#cancelSubscriptionsByName, [namePattern]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
