// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/screens/profile_setup_cancel_navigation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i13;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:nostr_sdk/event.dart' as _i7;
import 'package:nostr_sdk/filter.dart' as _i9;
import 'package:openvine/models/nip94_metadata.dart' as _i10;
import 'package:openvine/models/user_profile.dart' as _i11;
import 'package:openvine/services/auth_service.dart' as _i2;
import 'package:openvine/services/nostr_key_manager.dart' as _i3;
import 'package:openvine/services/nostr_service_interface.dart' as _i4;
import 'package:openvine/services/profile_cache_service.dart' as _i12;
import 'package:openvine/services/user_profile_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrKeyManager_1 extends _i1.SmartFake
    implements _i3.NostrKeyManager {
  _FakeNostrKeyManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrBroadcastResult_2 extends _i1.SmartFake
    implements _i4.NostrBroadcastResult {
  _FakeNostrBroadcastResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _i2.AuthState.unauthenticated,
          )
          as _i2.AuthState);

  @override
  _i5.Stream<_i2.AuthState> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i5.Stream<_i2.AuthState>.empty(),
          )
          as _i5.Stream<_i2.AuthState>);

  @override
  _i5.Stream<_i2.UserProfile?> get profileStream =>
      (super.noSuchMethod(
            Invocation.getter(#profileStream),
            returnValue: _i5.Stream<_i2.UserProfile?>.empty(),
          )
          as _i5.Stream<_i2.UserProfile?>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> get userStats =>
      (super.noSuchMethod(
            Invocation.getter(#userStats),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.AuthResult> createNewIdentity({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#createNewIdentity, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i5.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#createNewIdentity, [], {
                  #biometricPrompt: biometricPrompt,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<_i2.AuthResult> importFromNsec(
    String? nsec, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromNsec,
              [nsec],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i5.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromNsec,
                  [nsec],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<_i2.AuthResult> importFromHex(
    String? privateKeyHex, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromHex,
              [privateKeyHex],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i5.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromHex,
                  [privateKeyHex],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.AuthResult>);

  @override
  _i5.Future<void> refreshCurrentProfile(
    _i6.UserProfileService? userProfileService,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentProfile, [userProfileService]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> signOut({bool? deleteKeys = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#deleteKeys: deleteKeys}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getPrivateKeyForSigning({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateKeyForSigning, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> exportNsec({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#exportNsec, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<_i7.Event?> createAndSignEvent({
    required int? kind,
    required String? content,
    List<List<String>>? tags,
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAndSignEvent, [], {
              #kind: kind,
              #content: content,
              #tags: tags,
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i5.Future<_i7.Event?>.value(),
          )
          as _i5.Future<_i7.Event?>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [INostrService].
///
/// See the documentation for Mockito's code generation for more information.
class MockINostrService extends _i1.Mock implements _i4.INostrService {
  MockINostrService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  _i3.NostrKeyManager get keyManager =>
      (super.noSuchMethod(
            Invocation.getter(#keyManager),
            returnValue: _FakeNostrKeyManager_1(
              this,
              Invocation.getter(#keyManager),
            ),
          )
          as _i3.NostrKeyManager);

  @override
  int get relayCount =>
      (super.noSuchMethod(Invocation.getter(#relayCount), returnValue: 0)
          as int);

  @override
  int get connectedRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  List<String> get relays =>
      (super.noSuchMethod(Invocation.getter(#relays), returnValue: <String>[])
          as List<String>);

  @override
  Map<String, dynamic> get relayStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatuses),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  Map<String, bool> get relayAuthStates =>
      (super.noSuchMethod(
            Invocation.getter(#relayAuthStates),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i5.Stream<Map<String, bool>> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i5.Stream<Map<String, bool>>.empty(),
          )
          as _i5.Stream<Map<String, bool>>);

  @override
  bool get isVineRelayAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isVineRelayAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  String get primaryRelay =>
      (super.noSuchMethod(
            Invocation.getter(#primaryRelay),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#primaryRelay),
            ),
          )
          as String);

  @override
  bool isRelayAuthenticated(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#isRelayAuthenticated, [relayUrl]),
            returnValue: false,
          )
          as bool);

  @override
  void setAuthTimeout(Duration? timeout) => super.noSuchMethod(
    Invocation.method(#setAuthTimeout, [timeout]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> initialize({List<String>? customRelays}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {#customRelays: customRelays}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<_i7.Event> subscribeToEvents({
    required List<_i9.Filter>? filters,
    bool? bypassLimits = false,
    void Function()? onEose,
    bool? allowReuse = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToEvents, [], {
              #filters: filters,
              #bypassLimits: bypassLimits,
              #onEose: onEose,
              #allowReuse: allowReuse,
            }),
            returnValue: _i5.Stream<_i7.Event>.empty(),
          )
          as _i5.Stream<_i7.Event>);

  @override
  _i5.Stream<_i7.Event> subscribeToEventsWithCustomJson({
    required List<Map<String, dynamic>>? filtersJson,
    String? subscriptionId,
    bool? bypassLimits = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToEventsWithCustomJson, [], {
              #filtersJson: filtersJson,
              #subscriptionId: subscriptionId,
              #bypassLimits: bypassLimits,
              #onEose: onEose,
            }),
            returnValue: _i5.Stream<_i7.Event>.empty(),
          )
          as _i5.Stream<_i7.Event>);

  @override
  _i5.Future<_i4.NostrBroadcastResult> broadcastEvent(_i7.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastEvent, [event]),
            returnValue: _i5.Future<_i4.NostrBroadcastResult>.value(
              _FakeNostrBroadcastResult_2(
                this,
                Invocation.method(#broadcastEvent, [event]),
              ),
            ),
          )
          as _i5.Future<_i4.NostrBroadcastResult>);

  @override
  _i5.Future<_i4.NostrBroadcastResult> publishFileMetadata({
    required _i10.NIP94Metadata? metadata,
    required String? content,
    List<String>? hashtags = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#publishFileMetadata, [], {
              #metadata: metadata,
              #content: content,
              #hashtags: hashtags,
            }),
            returnValue: _i5.Future<_i4.NostrBroadcastResult>.value(
              _FakeNostrBroadcastResult_2(
                this,
                Invocation.method(#publishFileMetadata, [], {
                  #metadata: metadata,
                  #content: content,
                  #hashtags: hashtags,
                }),
              ),
            ),
          )
          as _i5.Future<_i4.NostrBroadcastResult>);

  @override
  _i5.Future<bool> addRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#addRelay, [relayUrl]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> removeRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelay, [relayUrl]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<String, bool> getRelayStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStatus, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i5.Future<void> reconnectAll() =>
      (super.noSuchMethod(
            Invocation.method(#reconnectAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> retryInitialization() =>
      (super.noSuchMethod(
            Invocation.method(#retryInitialization, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> closeAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#closeAllSubscriptions, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.Event>> getEvents({
    required List<_i9.Filter>? filters,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, [], {
              #filters: filters,
              #limit: limit,
            }),
            returnValue: _i5.Future<List<_i7.Event>>.value(<_i7.Event>[]),
          )
          as _i5.Future<List<_i7.Event>>);

  @override
  _i5.Future<_i7.Event?> fetchEventById(String? eventId, {String? relayUrl}) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEventById,
              [eventId],
              {#relayUrl: relayUrl},
            ),
            returnValue: _i5.Future<_i7.Event?>.value(),
          )
          as _i5.Future<_i7.Event?>);

  @override
  _i5.Future<List<_i7.Event>> queryEventsWithCustomJson({
    required List<Map<String, dynamic>>? filtersJson,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queryEventsWithCustomJson, [], {
              #filtersJson: filtersJson,
            }),
            returnValue: _i5.Future<List<_i7.Event>>.value(<_i7.Event>[]),
          )
          as _i5.Future<List<_i7.Event>>);

  @override
  _i5.Stream<_i7.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i5.Stream<_i7.Event>.empty(),
          )
          as _i5.Stream<_i7.Event>);

  @override
  _i5.Future<Map<String, dynamic>?> getRelayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStats, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i6.UserProfileService {
  MockUserProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i11.UserProfile> get allProfiles =>
      (super.noSuchMethod(
            Invocation.getter(#allProfiles),
            returnValue: <String, _i11.UserProfile>{},
          )
          as Map<String, _i11.UserProfile>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setPersistentCache(_i12.ProfileCacheService? cacheService) =>
      super.noSuchMethod(
        Invocation.method(#setPersistentCache, [cacheService]),
        returnValueForMissingStub: null,
      );

  @override
  _i11.UserProfile? getCachedProfile(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(#getCachedProfile, [pubkey]))
          as _i11.UserProfile?);

  @override
  bool hasProfile(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#hasProfile, [pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  bool shouldSkipProfileFetch(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#shouldSkipProfileFetch, [pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  void markProfileAsMissing(String? pubkey) => super.noSuchMethod(
    Invocation.method(#markProfileAsMissing, [pubkey]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> updateCachedProfile(_i11.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateCachedProfile, [profile]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i11.UserProfile?> fetchProfile(
    String? pubkey, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchProfile,
              [pubkey],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i5.Future<_i11.UserProfile?>.value(),
          )
          as _i5.Future<_i11.UserProfile?>);

  @override
  _i5.Future<void> prefetchProfilesImmediately(List<String>? pubkeys) =>
      (super.noSuchMethod(
            Invocation.method(#prefetchProfilesImmediately, [pubkeys]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchMultipleProfiles(
    List<String>? pubkeys, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchMultipleProfiles,
              [pubkeys],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String getDisplayName(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getDisplayName, [pubkey]),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getDisplayName, [pubkey]),
            ),
          )
          as String);

  @override
  String? getAvatarUrl(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(#getAvatarUrl, [pubkey]))
          as String?);

  @override
  String? getUserBio(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(#getUserBio, [pubkey])) as String?);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeProfile(String? pubkey) => super.noSuchMethod(
    Invocation.method(#removeProfile, [pubkey]),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void handleProfileEventForTesting(_i7.Event? event) => super.noSuchMethod(
    Invocation.method(#handleProfileEventForTesting, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
