// Mocks generated by Mockito 5.4.5 from annotations
// in openvine/test/screens/relay_settings_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:nostr_sdk/event.dart' as _i7;
import 'package:nostr_sdk/filter.dart' as _i8;
import 'package:openvine/models/nip94_metadata.dart' as _i9;
import 'package:openvine/services/nostr_key_manager.dart' as _i2;
import 'package:openvine/services/nostr_service.dart' as _i4;
import 'package:openvine/services/nostr_service_interface.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNostrKeyManager_0 extends _i1.SmartFake
    implements _i2.NostrKeyManager {
  _FakeNostrKeyManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNostrBroadcastResult_1 extends _i1.SmartFake
    implements _i3.NostrBroadcastResult {
  _FakeNostrBroadcastResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NostrService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrService extends _i1.Mock implements _i4.NostrService {
  MockNostrService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
      ) as bool);

  @override
  List<String> get connectedRelays => (super.noSuchMethod(
        Invocation.getter(#connectedRelays),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get hasKeys => (super.noSuchMethod(
        Invocation.getter(#hasKeys),
        returnValue: false,
      ) as bool);

  @override
  _i2.NostrKeyManager get keyManager => (super.noSuchMethod(
        Invocation.getter(#keyManager),
        returnValue: _FakeNostrKeyManager_0(
          this,
          Invocation.getter(#keyManager),
        ),
      ) as _i2.NostrKeyManager);

  @override
  int get relayCount => (super.noSuchMethod(
        Invocation.getter(#relayCount),
        returnValue: 0,
      ) as int);

  @override
  int get connectedRelayCount => (super.noSuchMethod(
        Invocation.getter(#connectedRelayCount),
        returnValue: 0,
      ) as int);

  @override
  List<String> get relays => (super.noSuchMethod(
        Invocation.getter(#relays),
        returnValue: <String>[],
      ) as List<String>);

  @override
  Map<String, dynamic> get relayStatuses => (super.noSuchMethod(
        Invocation.getter(#relayStatuses),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, bool> get relayAuthStates => (super.noSuchMethod(
        Invocation.getter(#relayAuthStates),
        returnValue: <String, bool>{},
      ) as Map<String, bool>);

  @override
  _i5.Stream<Map<String, bool>> get authStateStream => (super.noSuchMethod(
        Invocation.getter(#authStateStream),
        returnValue: _i5.Stream<Map<String, bool>>.empty(),
      ) as _i5.Stream<Map<String, bool>>);

  @override
  bool get isVineRelayAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isVineRelayAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  String get primaryRelay => (super.noSuchMethod(
        Invocation.getter(#primaryRelay),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#primaryRelay),
        ),
      ) as String);

  @override
  String get serviceName => (super.noSuchMethod(
        Invocation.getter(#serviceName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#serviceName),
        ),
      ) as String);

  @override
  bool isRelayAuthenticated(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #isRelayAuthenticated,
          [relayUrl],
        ),
        returnValue: false,
      ) as bool);

  @override
  void setAuthTimeout(Duration? timeout) => super.noSuchMethod(
        Invocation.method(
          #setAuthTimeout,
          [timeout],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> initialize({List<String>? customRelays}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {#customRelays: customRelays},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<_i7.Event> subscribeToEvents({
    required List<_i8.Filter>? filters,
    bool? bypassLimits = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToEvents,
          [],
          {
            #filters: filters,
            #bypassLimits: bypassLimits,
          },
        ),
        returnValue: _i5.Stream<_i7.Event>.empty(),
      ) as _i5.Stream<_i7.Event>);

  @override
  _i5.Future<_i3.NostrBroadcastResult> broadcastEvent(_i7.Event? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #broadcastEvent,
          [event],
        ),
        returnValue: _i5.Future<_i3.NostrBroadcastResult>.value(
            _FakeNostrBroadcastResult_1(
          this,
          Invocation.method(
            #broadcastEvent,
            [event],
          ),
        )),
      ) as _i5.Future<_i3.NostrBroadcastResult>);

  @override
  _i5.Future<_i3.NostrBroadcastResult> publishFileMetadata({
    required _i9.NIP94Metadata? metadata,
    required String? content,
    List<String>? hashtags = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishFileMetadata,
          [],
          {
            #metadata: metadata,
            #content: content,
            #hashtags: hashtags,
          },
        ),
        returnValue: _i5.Future<_i3.NostrBroadcastResult>.value(
            _FakeNostrBroadcastResult_1(
          this,
          Invocation.method(
            #publishFileMetadata,
            [],
            {
              #metadata: metadata,
              #content: content,
              #hashtags: hashtags,
            },
          ),
        )),
      ) as _i5.Future<_i3.NostrBroadcastResult>);

  @override
  _i5.Future<bool> addRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #addRelay,
          [relayUrl],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> removeRelay(String? relayUrl) => (super.noSuchMethod(
        Invocation.method(
          #removeRelay,
          [relayUrl],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, bool> getRelayStatus() => (super.noSuchMethod(
        Invocation.method(
          #getRelayStatus,
          [],
        ),
        returnValue: <String, bool>{},
      ) as Map<String, bool>);

  @override
  _i5.Future<void> reconnectAll() => (super.noSuchMethod(
        Invocation.method(
          #reconnectAll,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, dynamic> getConnectionStatus() => (super.noSuchMethod(
        Invocation.method(
          #getConnectionStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> getDetailedRelayStatus() => (super.noSuchMethod(
        Invocation.method(
          #getDetailedRelayStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<void> closeAllSubscriptions() => (super.noSuchMethod(
        Invocation.method(
          #closeAllSubscriptions,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearPersistedAuthStates() => (super.noSuchMethod(
        Invocation.method(
          #clearPersistedAuthStates,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void onAppBackgrounded() => super.noSuchMethod(
        Invocation.method(
          #onAppBackgrounded,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onExtendedBackground() => super.noSuchMethod(
        Invocation.method(
          #onExtendedBackground,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onAppResumed() => super.noSuchMethod(
        Invocation.method(
          #onAppResumed,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onPeriodicCleanup() => super.noSuchMethod(
        Invocation.method(
          #onPeriodicCleanup,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<_i7.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVideos,
          [query],
          {
            #authors: authors,
            #since: since,
            #until: until,
            #limit: limit,
          },
        ),
        returnValue: _i5.Stream<_i7.Event>.empty(),
      ) as _i5.Stream<_i7.Event>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
