// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/screens/search_screen_hybrid_search_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i10;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:nostr_sdk/event.dart' as _i7;
import 'package:openvine/models/user_profile.dart' as _i12;
import 'package:openvine/models/video_event.dart' as _i3;
import 'package:openvine/services/age_verification_service.dart' as _i6;
import 'package:openvine/services/content_blocklist_service.dart' as _i5;
import 'package:openvine/services/profile_cache_service.dart' as _i13;
import 'package:openvine/services/user_profile_service.dart' as _i11;
import 'package:openvine/services/video_event_service.dart' as _i2;
import 'package:openvine/services/video_filter_builder.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [VideoEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoEventService extends _i1.Mock implements _i2.VideoEventService {
  @override
  bool get shouldFilterAdultContent =>
      (super.noSuchMethod(
            Invocation.getter(#shouldFilterAdultContent),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i3.VideoEvent> get homeFeedVideos =>
      (super.noSuchMethod(
            Invocation.getter(#homeFeedVideos),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  List<_i3.VideoEvent> get discoveryVideos =>
      (super.noSuchMethod(
            Invocation.getter(#discoveryVideos),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  List<_i3.VideoEvent> get profileVideos =>
      (super.noSuchMethod(
            Invocation.getter(#profileVideos),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  List<_i3.VideoEvent> get editorialVideos =>
      (super.noSuchMethod(
            Invocation.getter(#editorialVideos),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  List<_i3.VideoEvent> get popularNowVideos =>
      (super.noSuchMethod(
            Invocation.getter(#popularNowVideos),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  List<_i3.VideoEvent> get trendingVideos =>
      (super.noSuchMethod(
            Invocation.getter(#trendingVideos),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  List<_i3.VideoEvent> get allHashtagVideos =>
      (super.noSuchMethod(
            Invocation.getter(#allHashtagVideos),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  List<_i3.VideoEvent> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  List<_i3.VideoEvent> get videoEvents =>
      (super.noSuchMethod(
            Invocation.getter(#videoEvents),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get classicVinesPubkey =>
      (super.noSuchMethod(
            Invocation.getter(#classicVinesPubkey),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#classicVinesPubkey),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.getter(#classicVinesPubkey),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setBlocklistService(_i5.ContentBlocklistService? blocklistService) =>
      super.noSuchMethod(
        Invocation.method(#setBlocklistService, [blocklistService]),
        returnValueForMissingStub: null,
      );

  @override
  void setAgeVerificationService(
    _i6.AgeVerificationService? ageVerificationService,
  ) => super.noSuchMethod(
    Invocation.method(#setAgeVerificationService, [ageVerificationService]),
    returnValueForMissingStub: null,
  );

  @override
  bool shouldFilterEvent(_i7.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#shouldFilterEvent, [event]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int filterAdultContentFromExistingVideos() =>
      (super.noSuchMethod(
            Invocation.method(#filterAdultContentFromExistingVideos, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  List<_i3.VideoEvent> getVideos(_i2.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getVideos, [type]),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  List<_i3.VideoEvent> hashtagVideos(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#hashtagVideos, [tag]),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  void debugDumpCdnDivineVideoThumbnails() => super.noSuchMethod(
    Invocation.method(#debugDumpCdnDivineVideoThumbnails, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i3.VideoEvent> authorVideos(String? pubkeyHex) =>
      (super.noSuchMethod(
            Invocation.method(#authorVideos, [pubkeyHex]),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  bool isLoadingForSubscription(_i2.SubscriptionType? subscriptionType) =>
      (super.noSuchMethod(
            Invocation.method(#isLoadingForSubscription, [subscriptionType]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool hasEvents(_i2.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#hasEvents, [type]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int getEventCount(_i2.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#getEventCount, [type]),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i3.VideoEvent? getVideoById(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoById, [eventId]),
            returnValueForMissingStub: null,
          )
          as _i3.VideoEvent?);

  @override
  bool isSubscribed(_i2.SubscriptionType? type) =>
      (super.noSuchMethod(
            Invocation.method(#isSubscribed, [type]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i3.VideoEvent> getVideosByAuthor(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getVideosByAuthor, [pubkey]),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  void removeVideoFromAuthorList(String? authorPubkey, String? videoId) =>
      super.noSuchMethod(
        Invocation.method(#removeVideoFromAuthorList, [authorPubkey, videoId]),
        returnValueForMissingStub: null,
      );

  @override
  bool isVideoLocallyDeleted(String? videoId) =>
      (super.noSuchMethod(
            Invocation.method(#isVideoLocallyDeleted, [videoId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<List<String>> getRepostersForVideo(String? videoId) =>
      (super.noSuchMethod(
            Invocation.method(#getRepostersForVideo, [videoId]),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  _i8.Future<void> subscribeToVideoFeed({
    required _i2.SubscriptionType? subscriptionType,
    List<String>? authors,
    List<String>? hashtags,
    String? group,
    int? since,
    int? until,
    int? limit = 200,
    bool? replace = true,
    bool? includeReposts = false,
    _i9.VideoSortField? sortBy,
    _i9.NIP50SortMode? nip50Sort,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToVideoFeed, [], {
              #subscriptionType: subscriptionType,
              #authors: authors,
              #hashtags: hashtags,
              #group: group,
              #since: since,
              #until: until,
              #limit: limit,
              #replace: replace,
              #includeReposts: includeReposts,
              #sortBy: sortBy,
              #nip50Sort: nip50Sort,
              #force: force,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> subscribeToUserVideos(String? pubkey, {int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToUserVideos,
              [pubkey],
              {#limit: limit},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> queryHistoricalUserVideos(
    String? pubkey, {
    int? until,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryHistoricalUserVideos,
              [pubkey],
              {#until: until, #limit: limit},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> subscribeToHashtagVideos(
    List<String>? hashtags, {
    int? limit = 100,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToHashtagVideos,
              [hashtags],
              {#limit: limit, #force: force},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> subscribeToHomeFeed(
    List<String>? followingPubkeys, {
    int? limit = 100,
    _i9.VideoSortField? sortBy,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToHomeFeed,
              [followingPubkeys],
              {#limit: limit, #sortBy: sortBy, #force: force},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> subscribeToDiscovery({
    int? limit = 100,
    _i9.VideoSortField? sortBy,
    _i9.NIP50SortMode? nip50Sort,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToDiscovery, [], {
              #limit: limit,
              #sortBy: sortBy,
              #nip50Sort: nip50Sort,
              #force: force,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> subscribeToGroupVideos(
    String? group, {
    List<String>? authors,
    int? since,
    int? until,
    int? limit = 200,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribeToGroupVideos,
              [group],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  List<_i3.VideoEvent> getVideoEventsByGroup(String? group) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByGroup, [group]),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  _i8.Future<void> refreshVideoFeed() =>
      (super.noSuchMethod(
            Invocation.method(#refreshVideoFeed, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> loadMoreVideos({int? limit = 100}) =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreVideos, [], {#limit: limit}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> loadMoreEvents(
    _i2.SubscriptionType? subscriptionType, {
    int? limit = 500,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadMoreEvents,
              [subscriptionType],
              {#limit: limit},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void resetPaginationState(_i2.SubscriptionType? subscriptionType) =>
      super.noSuchMethod(
        Invocation.method(#resetPaginationState, [subscriptionType]),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> loadMoreContentUnlimited({
    _i2.SubscriptionType? subscriptionType = _i2.SubscriptionType.discovery,
    int? limit = 300,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreContentUnlimited, [], {
              #subscriptionType: subscriptionType,
              #limit: limit,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i3.VideoEvent? getVideoEventById(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventById, [eventId]),
            returnValueForMissingStub: null,
          )
          as _i3.VideoEvent?);

  @override
  _i3.VideoEvent? getVideoEventByVineId(String? vineId) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventByVineId, [vineId]),
            returnValueForMissingStub: null,
          )
          as _i3.VideoEvent?);

  @override
  _i8.Future<_i3.VideoEvent?> queryVideoByVineId(String? vineId) =>
      (super.noSuchMethod(
            Invocation.method(#queryVideoByVineId, [vineId]),
            returnValue: _i8.Future<_i3.VideoEvent?>.value(),
            returnValueForMissingStub: _i8.Future<_i3.VideoEvent?>.value(),
          )
          as _i8.Future<_i3.VideoEvent?>);

  @override
  List<_i3.VideoEvent> getVideoEventsByAuthor(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByAuthor, [pubkey]),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  List<_i3.VideoEvent> getVideoEventsByHashtags(List<String>? hashtags) =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByHashtags, [hashtags]),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  void clearVideoEvents() => super.noSuchMethod(
    Invocation.method(#clearVideoEvents, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> unsubscribeFromVideoFeed() =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromVideoFeed, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  List<_i3.VideoEvent> getVideoEventsByEngagement() =>
      (super.noSuchMethod(
            Invocation.method(#getVideoEventsByEngagement, []),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  List<_i3.VideoEvent> getRecentVideoEvents({int? hours = 24}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentVideoEvents, [], {#hours: hours}),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  Set<String> getUniqueAuthors() =>
      (super.noSuchMethod(
            Invocation.method(#getUniqueAuthors, []),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  Set<String> getAllHashtags() =>
      (super.noSuchMethod(
            Invocation.method(#getAllHashtags, []),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  Map<String, int> getVideoCountByAuthor() =>
      (super.noSuchMethod(
            Invocation.method(#getVideoCountByAuthor, []),
            returnValue: <String, int>{},
            returnValueForMissingStub: <String, int>{},
          )
          as Map<String, int>);

  @override
  Map<String, dynamic> getConnectionStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectionStatus, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i8.Future<void> retrySubscription() =>
      (super.noSuchMethod(
            Invocation.method(#retrySubscription, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void shuffleForDiscovery() => super.noSuchMethod(
    Invocation.method(#shuffleForDiscovery, []),
    returnValueForMissingStub: null,
  );

  @override
  void addVideoEvent(_i3.VideoEvent? videoEvent) => super.noSuchMethod(
    Invocation.method(#addVideoEvent, [videoEvent]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> searchVideosByHashtag(String? hashtag) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosByHashtag, [hashtag]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> searchVideosWithFilters({
    required String? query,
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosWithFilters, [], {
              #query: query,
              #authors: authors,
              #since: since,
              #until: until,
              #limit: limit,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void clearSearchResults() => super.noSuchMethod(
    Invocation.method(#clearSearchResults, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i3.VideoEvent> processSearchResults(List<_i7.Event>? events) =>
      (super.noSuchMethod(
            Invocation.method(#processSearchResults, [events]),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  List<_i3.VideoEvent> deduplicateSearchResults(
    List<_i3.VideoEvent>? results,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deduplicateSearchResults, [results]),
            returnValue: <_i3.VideoEvent>[],
            returnValueForMissingStub: <_i3.VideoEvent>[],
          )
          as List<_i3.VideoEvent>);

  @override
  _i8.Future<void> searchVideosWithTimeRange({
    required String? query,
    required DateTime? since,
    required DateTime? until,
    List<String>? authors,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosWithTimeRange, [], {
              #query: query,
              #since: since,
              #until: until,
              #authors: authors,
              #limit: limit,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> searchVideosWithExtensions(String? queryWithExtensions) =>
      (super.noSuchMethod(
            Invocation.method(#searchVideosWithExtensions, [
              queryWithExtensions,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  Map<_i2.SubscriptionType, _i2.PaginationState>
  getPaginationStatesForTesting() =>
      (super.noSuchMethod(
            Invocation.method(#getPaginationStatesForTesting, []),
            returnValue: <_i2.SubscriptionType, _i2.PaginationState>{},
            returnValueForMissingStub:
                <_i2.SubscriptionType, _i2.PaginationState>{},
          )
          as Map<_i2.SubscriptionType, _i2.PaginationState>);

  @override
  void addVideoEventForTesting(
    _i3.VideoEvent? event,
    _i2.SubscriptionType? type, {
    required bool? isHistorical,
  }) => super.noSuchMethod(
    Invocation.method(
      #addVideoEventForTesting,
      [event, type],
      {#isHistorical: isHistorical},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void injectTestVideos(List<_i3.VideoEvent>? videos) => super.noSuchMethod(
    Invocation.method(#injectTestVideos, [videos]),
    returnValueForMissingStub: null,
  );

  @override
  void handleEventForTesting(_i7.Event? event, _i2.SubscriptionType? type) =>
      super.noSuchMethod(
        Invocation.method(#handleEventForTesting, [event, type]),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i11.UserProfileService {
  @override
  Map<String, _i12.UserProfile> get allProfiles =>
      (super.noSuchMethod(
            Invocation.getter(#allProfiles),
            returnValue: <String, _i12.UserProfile>{},
            returnValueForMissingStub: <String, _i12.UserProfile>{},
          )
          as Map<String, _i12.UserProfile>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void setPersistentCache(_i13.ProfileCacheService? cacheService) =>
      super.noSuchMethod(
        Invocation.method(#setPersistentCache, [cacheService]),
        returnValueForMissingStub: null,
      );

  @override
  _i12.UserProfile? getCachedProfile(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProfile, [pubkey]),
            returnValueForMissingStub: null,
          )
          as _i12.UserProfile?);

  @override
  bool hasProfile(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#hasProfile, [pubkey]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool shouldSkipProfileFetch(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#shouldSkipProfileFetch, [pubkey]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void markProfileAsMissing(String? pubkey) => super.noSuchMethod(
    Invocation.method(#markProfileAsMissing, [pubkey]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> updateCachedProfile(_i12.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateCachedProfile, [profile]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i12.UserProfile?> fetchProfile(
    String? pubkey, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchProfile,
              [pubkey],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i8.Future<_i12.UserProfile?>.value(),
            returnValueForMissingStub: _i8.Future<_i12.UserProfile?>.value(),
          )
          as _i8.Future<_i12.UserProfile?>);

  @override
  _i8.Future<void> prefetchProfilesImmediately(List<String>? pubkeys) =>
      (super.noSuchMethod(
            Invocation.method(#prefetchProfilesImmediately, [pubkeys]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> fetchMultipleProfiles(
    List<String>? pubkeys, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchMultipleProfiles,
              [pubkeys],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  String getDisplayName(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getDisplayName, [pubkey]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getDisplayName, [pubkey]),
            ),
            returnValueForMissingStub: _i4.dummyValue<String>(
              this,
              Invocation.method(#getDisplayName, [pubkey]),
            ),
          )
          as String);

  @override
  String? getAvatarUrl(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getAvatarUrl, [pubkey]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  String? getUserBio(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getUserBio, [pubkey]),
            returnValueForMissingStub: null,
          )
          as String?);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeProfile(String? pubkey) => super.noSuchMethod(
    Invocation.method(#removeProfile, [pubkey]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<List<_i12.UserProfile>> searchUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i8.Future<List<_i12.UserProfile>>.value(
              <_i12.UserProfile>[],
            ),
            returnValueForMissingStub: _i8.Future<List<_i12.UserProfile>>.value(
              <_i12.UserProfile>[],
            ),
          )
          as _i8.Future<List<_i12.UserProfile>>);

  @override
  Map<String, dynamic> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void handleProfileEventForTesting(_i7.Event? event) => super.noSuchMethod(
    Invocation.method(#handleProfileEventForTesting, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
