// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/screens/video_metadata_screen_publish_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:models/models.dart' as _i7;
import 'package:openvine/models/pending_upload.dart' as _i2;
import 'package:openvine/models/vine_draft.dart' as _i5;
import 'package:openvine/services/upload_manager.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePendingUpload_0 extends _i1.SmartFake implements _i2.PendingUpload {
  _FakePendingUpload_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UploadManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadManager extends _i1.Mock implements _i3.UploadManager {
  MockUploadManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  List<_i2.PendingUpload> get pendingUploads =>
      (super.noSuchMethod(
            Invocation.getter(#pendingUploads),
            returnValue: <_i2.PendingUpload>[],
          )
          as List<_i2.PendingUpload>);

  @override
  List<_i2.PendingUpload> get uploadsReadyForProcessing =>
      (super.noSuchMethod(
            Invocation.getter(#uploadsReadyForProcessing),
            returnValue: <_i2.PendingUpload>[],
          )
          as List<_i2.PendingUpload>);

  @override
  Map<String, int> get uploadStats =>
      (super.noSuchMethod(
            Invocation.getter(#uploadStats),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  _i4.Future<void> setUploadTarget(dynamic target) =>
      (super.noSuchMethod(
            Invocation.method(#setUploadTarget, [target]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isBlossomAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isBlossomAvailable, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  List<_i2.PendingUpload> getUploadsByStatus(_i2.UploadStatus? status) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadsByStatus, [status]),
            returnValue: <_i2.PendingUpload>[],
          )
          as List<_i2.PendingUpload>);

  @override
  _i2.PendingUpload? getUpload(String? id) =>
      (super.noSuchMethod(Invocation.method(#getUpload, [id]))
          as _i2.PendingUpload?);

  @override
  _i2.PendingUpload? getUploadByFilePath(String? filePath) =>
      (super.noSuchMethod(Invocation.method(#getUploadByFilePath, [filePath]))
          as _i2.PendingUpload?);

  @override
  _i4.Future<void> markUploadPublished(
    String? uploadId,
    String? nostrEventId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markUploadPublished, [uploadId, nostrEventId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markUploadReadyToPublish(
    String? uploadId,
    String? cloudinaryPublicId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markUploadReadyToPublish, [
              uploadId,
              cloudinaryPublicId,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.PendingUpload> startUploadFromDraft({
    required _i5.VineDraft? draft,
    required String? nostrPubkey,
    Duration? videoDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startUploadFromDraft, [], {
              #draft: draft,
              #nostrPubkey: nostrPubkey,
              #videoDuration: videoDuration,
            }),
            returnValue: _i4.Future<_i2.PendingUpload>.value(
              _FakePendingUpload_0(
                this,
                Invocation.method(#startUploadFromDraft, [], {
                  #draft: draft,
                  #nostrPubkey: nostrPubkey,
                  #videoDuration: videoDuration,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.PendingUpload>);

  @override
  _i4.Future<_i2.PendingUpload> startUpload({
    required _i6.File? videoFile,
    required String? nostrPubkey,
    String? thumbnailPath,
    String? title,
    String? description,
    List<String>? hashtags,
    int? videoWidth,
    int? videoHeight,
    Duration? videoDuration,
    _i7.NativeProofData? nativeProof,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startUpload, [], {
              #videoFile: videoFile,
              #nostrPubkey: nostrPubkey,
              #thumbnailPath: thumbnailPath,
              #title: title,
              #description: description,
              #hashtags: hashtags,
              #videoWidth: videoWidth,
              #videoHeight: videoHeight,
              #videoDuration: videoDuration,
              #nativeProof: nativeProof,
            }),
            returnValue: _i4.Future<_i2.PendingUpload>.value(
              _FakePendingUpload_0(
                this,
                Invocation.method(#startUpload, [], {
                  #videoFile: videoFile,
                  #nostrPubkey: nostrPubkey,
                  #thumbnailPath: thumbnailPath,
                  #title: title,
                  #description: description,
                  #hashtags: hashtags,
                  #videoWidth: videoWidth,
                  #videoHeight: videoHeight,
                  #videoDuration: videoDuration,
                  #nativeProof: nativeProof,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.PendingUpload>);

  @override
  _i4.Future<void> pauseUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#pauseUpload, [uploadId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resumeUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeUpload, [uploadId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> retryUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#retryUpload, [uploadId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelUpload, [uploadId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUpload(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUpload, [uploadId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cleanupCompletedUploads() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupCompletedUploads, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUploadStatus(
    String? uploadId,
    _i2.UploadStatus? status, {
    String? nostrEventId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUploadStatus,
              [uploadId, status],
              {#nostrEventId: nostrEventId},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateUploadMetadata(
    String? uploadId, {
    String? title,
    String? description,
    List<String>? hashtags,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUploadMetadata,
              [uploadId],
              {#title: title, #description: description, #hashtags: hashtags},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cleanupProblematicUploads() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupProblematicUploads, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  Map<String, dynamic> getPerformanceMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceMetrics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.UploadMetrics? getUploadMetrics(String? uploadId) =>
      (super.noSuchMethod(Invocation.method(#getUploadMetrics, [uploadId]))
          as _i3.UploadMetrics?);

  @override
  List<_i3.UploadMetrics> getRecentMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentMetrics, []),
            returnValue: <_i3.UploadMetrics>[],
          )
          as List<_i3.UploadMetrics>);

  @override
  _i4.Future<void> retryUploadWithBackoff(String? uploadId) =>
      (super.noSuchMethod(
            Invocation.method(#retryUploadWithBackoff, [uploadId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
