// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/helpers/follow_actions_helper_simple_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nostr_sdk/event.dart' as _i5;
import 'package:openvine/models/video_event.dart' as _i6;
import 'package:openvine/services/auth_service.dart' as _i2;
import 'package:openvine/services/social_service.dart' as _i3;
import 'package:openvine/services/user_profile_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SocialService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialService extends _i1.Mock implements _i3.SocialService {
  MockSocialService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> get likedEventIds =>
      (super.noSuchMethod(
            Invocation.getter(#likedEventIds),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  List<String> get followingPubkeys =>
      (super.noSuchMethod(
            Invocation.getter(#followingPubkeys),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<_i3.FollowSet> get followSets =>
      (super.noSuchMethod(
            Invocation.getter(#followSets),
            returnValue: <_i3.FollowSet>[],
          )
          as List<_i3.FollowSet>);

  @override
  bool isLiked(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#isLiked, [eventId]),
            returnValue: false,
          )
          as bool);

  @override
  bool hasReposted(String? eventId, {String? pubkey, String? dTag}) =>
      (super.noSuchMethod(
            Invocation.method(
              #hasReposted,
              [eventId],
              {#pubkey: pubkey, #dTag: dTag},
            ),
            returnValue: false,
          )
          as bool);

  @override
  int? getCachedLikeCount(String? eventId) =>
      (super.noSuchMethod(Invocation.method(#getCachedLikeCount, [eventId]))
          as int?);

  @override
  bool isFollowing(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#isFollowing, [pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, int>? getCachedFollowerStats(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(#getCachedFollowerStats, [pubkey]))
          as Map<String, int>?);

  @override
  _i3.FollowSet? getFollowSetById(String? setId) =>
      (super.noSuchMethod(Invocation.method(#getFollowSetById, [setId]))
          as _i3.FollowSet?);

  @override
  bool isInFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#isInFollowSet, [setId, pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> toggleLike(String? eventId, String? authorPubkey) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [eventId, authorPubkey]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getLikeStatus(String? eventId) =>
      (super.noSuchMethod(
            Invocation.method(#getLikeStatus, [eventId]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i5.Event>> fetchLikedEvents(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLikedEvents, [pubkey]),
            returnValue: _i4.Future<List<_i5.Event>>.value(<_i5.Event>[]),
          )
          as _i4.Future<List<_i5.Event>>);

  @override
  _i4.Future<void> fetchCurrentUserFollowList() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCurrentUserFollowList, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> followUser(String? pubkeyToFollow) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [pubkeyToFollow]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> unfollowUser(String? pubkeyToUnfollow) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [pubkeyToUnfollow]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, int>> getFollowerStats(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowerStats, [pubkey]),
            returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i4.Future<Map<String, int>>);

  @override
  _i4.Future<_i3.FollowSet?> createFollowSet({
    required String? name,
    String? description,
    String? imageUrl,
    List<String>? initialPubkeys = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createFollowSet, [], {
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #initialPubkeys: initialPubkeys,
            }),
            returnValue: _i4.Future<_i3.FollowSet?>.value(),
          )
          as _i4.Future<_i3.FollowSet?>);

  @override
  _i4.Future<bool> addToFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#addToFollowSet, [setId, pubkey]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeFromFollowSet(String? setId, String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromFollowSet, [setId, pubkey]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateFollowSet({
    required String? setId,
    String? name,
    String? description,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateFollowSet, [], {
              #setId: setId,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteFollowSet(String? setId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFollowSet, [setId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> getUserVideoCount(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getUserVideoCount, [pubkey]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getUserTotalLikes(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getUserTotalLikes, [pubkey]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> postComment({
    required String? content,
    required String? rootEventId,
    required String? rootEventAuthorPubkey,
    String? replyToEventId,
    String? replyToAuthorPubkey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#postComment, [], {
              #content: content,
              #rootEventId: rootEventId,
              #rootEventAuthorPubkey: rootEventAuthorPubkey,
              #replyToEventId: replyToEventId,
              #replyToAuthorPubkey: replyToAuthorPubkey,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i5.Event> fetchCommentsForEvent(String? rootEventId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCommentsForEvent, [rootEventId]),
            returnValue: _i4.Stream<_i5.Event>.empty(),
          )
          as _i4.Stream<_i5.Event>);

  @override
  _i4.Future<int> getCommentCount(String? rootEventId) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentCount, [rootEventId]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> cancelCommentSubscriptions(String? rootEventId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelCommentSubscriptions, [rootEventId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> toggleRepost(_i6.VideoEvent? videoToRepost) =>
      (super.noSuchMethod(
            Invocation.method(#toggleRepost, [videoToRepost]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> repostEvent(_i5.Event? eventToRepost) =>
      (super.noSuchMethod(
            Invocation.method(#repostEvent, [eventToRepost]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> publishRightToBeForgotten() =>
      (super.noSuchMethod(
            Invocation.method(#publishRightToBeForgotten, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _i2.AuthState.unauthenticated,
          )
          as _i2.AuthState);

  @override
  _i4.Stream<_i2.AuthState> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i4.Stream<_i2.AuthState>.empty(),
          )
          as _i4.Stream<_i2.AuthState>);

  @override
  _i4.Stream<_i2.UserProfile?> get profileStream =>
      (super.noSuchMethod(
            Invocation.getter(#profileStream),
            returnValue: _i4.Stream<_i2.UserProfile?>.empty(),
          )
          as _i4.Stream<_i2.UserProfile?>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> get userStats =>
      (super.noSuchMethod(
            Invocation.getter(#userStats),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.AuthResult> createNewIdentity({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#createNewIdentity, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#createNewIdentity, [], {
                  #biometricPrompt: biometricPrompt,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> importFromNsec(
    String? nsec, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromNsec,
              [nsec],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromNsec,
                  [nsec],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<_i2.AuthResult> importFromHex(
    String? privateKeyHex, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromHex,
              [privateKeyHex],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i4.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromHex,
                  [privateKeyHex],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.AuthResult>);

  @override
  _i4.Future<void> refreshCurrentProfile(
    _i7.UserProfileService? userProfileService,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentProfile, [userProfileService]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> acceptTermsOfService() =>
      (super.noSuchMethod(
            Invocation.method(#acceptTermsOfService, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> signOut({bool? deleteKeys = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#deleteKeys: deleteKeys}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getPrivateKeyForSigning({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateKeyForSigning, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> exportNsec({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#exportNsec, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<_i5.Event?> createAndSignEvent({
    required int? kind,
    required String? content,
    List<List<String>>? tags,
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAndSignEvent, [], {
              #kind: kind,
              #content: content,
              #tags: tags,
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i4.Future<_i5.Event?>.value(),
          )
          as _i4.Future<_i5.Event?>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
