// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/unit/services/nip17_message_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:nostr_client/src/models/models.dart' as _i3;
import 'package:nostr_client/src/nostr_client.dart' as _i6;
import 'package:nostr_key_manager/src/nostr_key_manager.dart' as _i2;
import 'package:nostr_sdk/nostr_sdk.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeKeychain_0 extends _i1.SmartFake implements _i2.Keychain {
  _FakeKeychain_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCountResult_1 extends _i1.SmartFake implements _i3.CountResult {
  _FakeCountResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrBroadcastResult_2 extends _i1.SmartFake
    implements _i3.NostrBroadcastResult {
  _FakeNostrBroadcastResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NostrKeyManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrKeyManager extends _i1.Mock implements _i2.NostrKeyManager {
  MockNostrKeyManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  bool get hasBackup =>
      (super.noSuchMethod(Invocation.getter(#hasBackup), returnValue: false)
          as bool);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Keychain> generateKeys() =>
      (super.noSuchMethod(
            Invocation.method(#generateKeys, []),
            returnValue: _i4.Future<_i2.Keychain>.value(
              _FakeKeychain_0(this, Invocation.method(#generateKeys, [])),
            ),
          )
          as _i4.Future<_i2.Keychain>);

  @override
  _i4.Future<_i2.Keychain> importPrivateKey(String? privateKey) =>
      (super.noSuchMethod(
            Invocation.method(#importPrivateKey, [privateKey]),
            returnValue: _i4.Future<_i2.Keychain>.value(
              _FakeKeychain_0(
                this,
                Invocation.method(#importPrivateKey, [privateKey]),
              ),
            ),
          )
          as _i4.Future<_i2.Keychain>);

  @override
  _i4.Future<_i2.Keychain> importFromNsec(String? nsec) =>
      (super.noSuchMethod(
            Invocation.method(#importFromNsec, [nsec]),
            returnValue: _i4.Future<_i2.Keychain>.value(
              _FakeKeychain_0(this, Invocation.method(#importFromNsec, [nsec])),
            ),
          )
          as _i4.Future<_i2.Keychain>);

  @override
  String exportPrivateKey() =>
      (super.noSuchMethod(
            Invocation.method(#exportPrivateKey, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#exportPrivateKey, []),
            ),
          )
          as String);

  @override
  String exportAsNsec() =>
      (super.noSuchMethod(
            Invocation.method(#exportAsNsec, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#exportAsNsec, []),
            ),
          )
          as String);

  @override
  _i4.Future<Map<String, dynamic>> replaceKeyWithBackup() =>
      (super.noSuchMethod(
            Invocation.method(#replaceKeyWithBackup, []),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> restoreFromBackup() =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromBackup, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearBackup() =>
      (super.noSuchMethod(
            Invocation.method(#clearBackup, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> createMnemonicBackup() =>
      (super.noSuchMethod(
            Invocation.method(#createMnemonicBackup, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<_i2.Keychain> restoreFromMnemonic(List<String>? mnemonic) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromMnemonic, [mnemonic]),
            returnValue: _i4.Future<_i2.Keychain>.value(
              _FakeKeychain_0(
                this,
                Invocation.method(#restoreFromMnemonic, [mnemonic]),
              ),
            ),
          )
          as _i4.Future<_i2.Keychain>);

  @override
  _i4.Future<bool> verifyBackup(List<String>? mnemonic, String? privateKey) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBackup, [mnemonic, privateKey]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> clearKeys() =>
      (super.noSuchMethod(
            Invocation.method(#clearKeys, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  Map<String, dynamic> getIdentitySummary() =>
      (super.noSuchMethod(
            Invocation.method(#getIdentitySummary, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [NostrClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrClient extends _i1.Mock implements _i6.NostrClient {
  MockNostrClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#publicKey),
            ),
          )
          as String);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  List<String> get configuredRelays =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get connectedRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  int get configuredRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  Map<String, _i3.RelayConnectionStatus> get relayStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatuses),
            returnValue: <String, _i3.RelayConnectionStatus>{},
          )
          as Map<String, _i3.RelayConnectionStatus>);

  @override
  _i4.Stream<Map<String, _i3.RelayConnectionStatus>> get relayStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatusStream),
            returnValue:
                _i4.Stream<Map<String, _i3.RelayConnectionStatus>>.empty(),
          )
          as _i4.Stream<Map<String, _i3.RelayConnectionStatus>>);

  @override
  String get primaryRelay =>
      (super.noSuchMethod(
            Invocation.getter(#primaryRelay),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#primaryRelay),
            ),
          )
          as String);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.Event?> publishEvent(
    _i7.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #publishEvent,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i4.Future<_i7.Event?>.value(),
          )
          as _i4.Future<_i7.Event?>);

  @override
  _i4.Future<List<_i7.Event>> queryEvents(
    List<_i7.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #useGateway: useGateway,
                #useCache: useCache,
              },
            ),
            returnValue: _i4.Future<List<_i7.Event>>.value(<_i7.Event>[]),
          )
          as _i4.Future<List<_i7.Event>>);

  @override
  _i4.Future<_i3.CountResult> countEvents(
    List<_i7.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #countEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #timeout: timeout,
              },
            ),
            returnValue: _i4.Future<_i3.CountResult>.value(
              _FakeCountResult_1(
                this,
                Invocation.method(
                  #countEvents,
                  [filters],
                  {
                    #subscriptionId: subscriptionId,
                    #tempRelays: tempRelays,
                    #relayTypes: relayTypes,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i3.CountResult>);

  @override
  _i4.Future<_i7.Event?> fetchEventById(
    String? eventId, {
    String? relayUrl,
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEventById,
              [eventId],
              {
                #relayUrl: relayUrl,
                #useGateway: useGateway,
                #useCache: useCache,
              },
            ),
            returnValue: _i4.Future<_i7.Event?>.value(),
          )
          as _i4.Future<_i7.Event?>);

  @override
  _i4.Future<_i7.Event?> fetchProfile(
    String? pubkey, {
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchProfile,
              [pubkey],
              {#useGateway: useGateway, #useCache: useCache},
            ),
            returnValue: _i4.Future<_i7.Event?>.value(),
          )
          as _i4.Future<_i7.Event?>);

  @override
  _i4.Stream<_i7.Event> subscribe(
    List<_i7.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribe,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #onEose: onEose,
              },
            ),
            returnValue: _i4.Stream<_i7.Event>.empty(),
          )
          as _i4.Stream<_i7.Event>);

  @override
  _i4.Future<void> unsubscribe(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [subscriptionId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> closeAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#closeAllSubscriptions, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> addRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#addRelay, [relayUrl]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> removeRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelay, [relayUrl]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<Map<String, dynamic>?> getRelayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStats, []),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> retryDisconnectedRelays() =>
      (super.noSuchMethod(
            Invocation.method(#retryDisconnectedRelays, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  Map<String, bool> getRelayStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStatus, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i4.Future<_i7.Event?> sendLike(
    String? eventId, {
    String? content,
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendLike,
              [eventId],
              {
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i4.Future<_i7.Event?>.value(),
          )
          as _i4.Future<_i7.Event?>);

  @override
  _i4.Future<_i7.Event?> sendRepost(
    String? eventId, {
    String? relayAddr,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendRepost,
              [eventId],
              {
                #relayAddr: relayAddr,
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i4.Future<_i7.Event?>.value(),
          )
          as _i4.Future<_i7.Event?>);

  @override
  _i4.Future<_i7.Event?> deleteEvent(
    String? eventId, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvent,
              [eventId],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i4.Future<_i7.Event?>.value(),
          )
          as _i4.Future<_i7.Event?>);

  @override
  _i4.Future<_i7.Event?> deleteEvents(
    List<String>? eventIds, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvents,
              [eventIds],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i4.Future<_i7.Event?>.value(),
          )
          as _i4.Future<_i7.Event?>);

  @override
  _i4.Future<_i7.Event?> sendContactList(
    _i7.ContactList? contacts,
    String? content, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendContactList,
              [contacts, content],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i4.Future<_i7.Event?>.value(),
          )
          as _i4.Future<_i7.Event?>);

  @override
  _i4.Stream<_i7.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i4.Stream<_i7.Event>.empty(),
          )
          as _i4.Stream<_i7.Event>);

  @override
  _i4.Stream<_i7.Event> searchUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i4.Stream<_i7.Event>.empty(),
          )
          as _i4.Stream<_i7.Event>);

  @override
  _i4.Future<_i3.NostrBroadcastResult> broadcast(
    _i7.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #broadcast,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i4.Future<_i3.NostrBroadcastResult>.value(
              _FakeNostrBroadcastResult_2(
                this,
                Invocation.method(
                  #broadcast,
                  [event],
                  {#targetRelays: targetRelays},
                ),
              ),
            ),
          )
          as _i4.Future<_i3.NostrBroadcastResult>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
