// Mocks generated by Mockito 5.4.5 from annotations
// in openvine/test/widgets/profile_screen_update_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i13;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:nostr_sdk/event.dart' as _i5;
import 'package:openvine/models/user_profile.dart' as _i6;
import 'package:openvine/models/video_event.dart' as _i11;
import 'package:openvine/services/auth_service.dart' as _i2;
import 'package:openvine/services/content_blocklist_service.dart' as _i12;
import 'package:openvine/services/profile_cache_service.dart' as _i7;
import 'package:openvine/services/social_service.dart' as _i9;
import 'package:openvine/services/user_profile_service.dart' as _i4;
import 'package:openvine/services/video_event_service.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get authState => (super.noSuchMethod(
        Invocation.getter(#authState),
        returnValue: _i2.AuthState.unauthenticated,
      ) as _i2.AuthState);

  @override
  _i3.Stream<_i2.AuthState> get authStateStream => (super.noSuchMethod(
        Invocation.getter(#authStateStream),
        returnValue: _i3.Stream<_i2.AuthState>.empty(),
      ) as _i3.Stream<_i2.AuthState>);

  @override
  _i3.Stream<_i2.UserProfile?> get profileStream => (super.noSuchMethod(
        Invocation.getter(#profileStream),
        returnValue: _i3.Stream<_i2.UserProfile?>.empty(),
      ) as _i3.Stream<_i2.UserProfile?>);

  @override
  bool get isAuthenticated => (super.noSuchMethod(
        Invocation.getter(#isAuthenticated),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> get userStats => (super.noSuchMethod(
        Invocation.getter(#userStats),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i2.AuthResult> createNewIdentity({String? biometricPrompt}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNewIdentity,
          [],
          {#biometricPrompt: biometricPrompt},
        ),
        returnValue: _i3.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #createNewIdentity,
            [],
            {#biometricPrompt: biometricPrompt},
          ),
        )),
      ) as _i3.Future<_i2.AuthResult>);

  @override
  _i3.Future<_i2.AuthResult> importFromNsec(
    String? nsec, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importFromNsec,
          [nsec],
          {#biometricPrompt: biometricPrompt},
        ),
        returnValue: _i3.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #importFromNsec,
            [nsec],
            {#biometricPrompt: biometricPrompt},
          ),
        )),
      ) as _i3.Future<_i2.AuthResult>);

  @override
  _i3.Future<_i2.AuthResult> importFromHex(
    String? privateKeyHex, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importFromHex,
          [privateKeyHex],
          {#biometricPrompt: biometricPrompt},
        ),
        returnValue: _i3.Future<_i2.AuthResult>.value(_FakeAuthResult_0(
          this,
          Invocation.method(
            #importFromHex,
            [privateKeyHex],
            {#biometricPrompt: biometricPrompt},
          ),
        )),
      ) as _i3.Future<_i2.AuthResult>);

  @override
  _i3.Future<void> refreshCurrentProfile(
          _i4.UserProfileService? userProfileService) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshCurrentProfile,
          [userProfileService],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> signOut({bool? deleteKeys = false}) => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
          {#deleteKeys: deleteKeys},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getPrivateKeyForSigning({String? biometricPrompt}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPrivateKeyForSigning,
          [],
          {#biometricPrompt: biometricPrompt},
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> exportNsec({String? biometricPrompt}) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportNsec,
          [],
          {#biometricPrompt: biometricPrompt},
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<_i5.Event?> createAndSignEvent({
    required int? kind,
    required String? content,
    List<List<String>>? tags,
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAndSignEvent,
          [],
          {
            #kind: kind,
            #content: content,
            #tags: tags,
            #biometricPrompt: biometricPrompt,
          },
        ),
        returnValue: _i3.Future<_i5.Event?>.value(),
      ) as _i3.Future<_i5.Event?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i4.UserProfileService {
  MockUserProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i6.UserProfile> get allProfiles => (super.noSuchMethod(
        Invocation.getter(#allProfiles),
        returnValue: <String, _i6.UserProfile>{},
      ) as Map<String, _i6.UserProfile>);

  @override
  void setPersistentCache(_i7.ProfileCacheService? cacheService) =>
      super.noSuchMethod(
        Invocation.method(
          #setPersistentCache,
          [cacheService],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.UserProfile? getCachedProfile(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedProfile,
        [pubkey],
      )) as _i6.UserProfile?);

  @override
  bool hasProfile(String? pubkey) => (super.noSuchMethod(
        Invocation.method(
          #hasProfile,
          [pubkey],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool shouldSkipProfileFetch(String? pubkey) => (super.noSuchMethod(
        Invocation.method(
          #shouldSkipProfileFetch,
          [pubkey],
        ),
        returnValue: false,
      ) as bool);

  @override
  void markProfileAsMissing(String? pubkey) => super.noSuchMethod(
        Invocation.method(
          #markProfileAsMissing,
          [pubkey],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> updateCachedProfile(_i6.UserProfile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCachedProfile,
          [profile],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i6.UserProfile?> fetchProfile(
    String? pubkey, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProfile,
          [pubkey],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i3.Future<_i6.UserProfile?>.value(),
      ) as _i3.Future<_i6.UserProfile?>);

  @override
  _i3.Future<void> prefetchProfilesImmediately(List<String>? pubkeys) =>
      (super.noSuchMethod(
        Invocation.method(
          #prefetchProfilesImmediately,
          [pubkeys],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> fetchMultipleProfiles(
    List<String>? pubkeys, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMultipleProfiles,
          [pubkeys],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  String getDisplayName(String? pubkey) => (super.noSuchMethod(
        Invocation.method(
          #getDisplayName,
          [pubkey],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayName,
            [pubkey],
          ),
        ),
      ) as String);

  @override
  String? getAvatarUrl(String? pubkey) => (super.noSuchMethod(Invocation.method(
        #getAvatarUrl,
        [pubkey],
      )) as String?);

  @override
  String? getUserBio(String? pubkey) => (super.noSuchMethod(Invocation.method(
        #getUserBio,
        [pubkey],
      )) as String?);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeProfile(String? pubkey) => super.noSuchMethod(
        Invocation.method(
          #removeProfile,
          [pubkey],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, dynamic> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SocialService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSocialService extends _i1.Mock implements _i9.SocialService {
  MockSocialService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> get likedEventIds => (super.noSuchMethod(
        Invocation.getter(#likedEventIds),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  List<String> get followingPubkeys => (super.noSuchMethod(
        Invocation.getter(#followingPubkeys),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<_i9.FollowSet> get followSets => (super.noSuchMethod(
        Invocation.getter(#followSets),
        returnValue: <_i9.FollowSet>[],
      ) as List<_i9.FollowSet>);

  @override
  bool isLiked(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #isLiked,
          [eventId],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool hasReposted(
    String? eventId, {
    String? pubkey,
    String? dTag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasReposted,
          [eventId],
          {
            #pubkey: pubkey,
            #dTag: dTag,
          },
        ),
        returnValue: false,
      ) as bool);

  @override
  int? getCachedLikeCount(String? eventId) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedLikeCount,
        [eventId],
      )) as int?);

  @override
  bool isFollowing(String? pubkey) => (super.noSuchMethod(
        Invocation.method(
          #isFollowing,
          [pubkey],
        ),
        returnValue: false,
      ) as bool);

  @override
  Map<String, int>? getCachedFollowerStats(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(
        #getCachedFollowerStats,
        [pubkey],
      )) as Map<String, int>?);

  @override
  _i9.FollowSet? getFollowSetById(String? setId) =>
      (super.noSuchMethod(Invocation.method(
        #getFollowSetById,
        [setId],
      )) as _i9.FollowSet?);

  @override
  bool isInFollowSet(
    String? setId,
    String? pubkey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isInFollowSet,
          [
            setId,
            pubkey,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> toggleLike(
    String? eventId,
    String? authorPubkey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleLike,
          [
            eventId,
            authorPubkey,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getLikeStatus(String? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikeStatus,
          [eventId],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<_i5.Event>> fetchLikedEvents(String? pubkey) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLikedEvents,
          [pubkey],
        ),
        returnValue: _i3.Future<List<_i5.Event>>.value(<_i5.Event>[]),
      ) as _i3.Future<List<_i5.Event>>);

  @override
  _i3.Future<void> fetchCurrentUserFollowList() => (super.noSuchMethod(
        Invocation.method(
          #fetchCurrentUserFollowList,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> followUser(String? pubkeyToFollow) => (super.noSuchMethod(
        Invocation.method(
          #followUser,
          [pubkeyToFollow],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> unfollowUser(String? pubkeyToUnfollow) =>
      (super.noSuchMethod(
        Invocation.method(
          #unfollowUser,
          [pubkeyToUnfollow],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, int>> getFollowerStats(String? pubkey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFollowerStats,
          [pubkey],
        ),
        returnValue: _i3.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i3.Future<Map<String, int>>);

  @override
  _i3.Future<_i9.FollowSet?> createFollowSet({
    required String? name,
    String? description,
    String? imageUrl,
    List<String>? initialPubkeys = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFollowSet,
          [],
          {
            #name: name,
            #description: description,
            #imageUrl: imageUrl,
            #initialPubkeys: initialPubkeys,
          },
        ),
        returnValue: _i3.Future<_i9.FollowSet?>.value(),
      ) as _i3.Future<_i9.FollowSet?>);

  @override
  _i3.Future<bool> addToFollowSet(
    String? setId,
    String? pubkey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addToFollowSet,
          [
            setId,
            pubkey,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> removeFromFollowSet(
    String? setId,
    String? pubkey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeFromFollowSet,
          [
            setId,
            pubkey,
          ],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateFollowSet({
    required String? setId,
    String? name,
    String? description,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFollowSet,
          [],
          {
            #setId: setId,
            #name: name,
            #description: description,
            #imageUrl: imageUrl,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteFollowSet(String? setId) => (super.noSuchMethod(
        Invocation.method(
          #deleteFollowSet,
          [setId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<int> getUserVideoCount(String? pubkey) => (super.noSuchMethod(
        Invocation.method(
          #getUserVideoCount,
          [pubkey],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getUserTotalLikes(String? pubkey) => (super.noSuchMethod(
        Invocation.method(
          #getUserTotalLikes,
          [pubkey],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> postComment({
    required String? content,
    required String? rootEventId,
    required String? rootEventAuthorPubkey,
    String? replyToEventId,
    String? replyToAuthorPubkey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postComment,
          [],
          {
            #content: content,
            #rootEventId: rootEventId,
            #rootEventAuthorPubkey: rootEventAuthorPubkey,
            #replyToEventId: replyToEventId,
            #replyToAuthorPubkey: replyToAuthorPubkey,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<_i5.Event> fetchCommentsForEvent(String? rootEventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchCommentsForEvent,
          [rootEventId],
        ),
        returnValue: _i3.Stream<_i5.Event>.empty(),
      ) as _i3.Stream<_i5.Event>);

  @override
  _i3.Future<int> getCommentCount(String? rootEventId) => (super.noSuchMethod(
        Invocation.method(
          #getCommentCount,
          [rootEventId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> cancelCommentSubscriptions(String? rootEventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelCommentSubscriptions,
          [rootEventId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> repostEvent(_i5.Event? eventToRepost) => (super.noSuchMethod(
        Invocation.method(
          #repostEvent,
          [eventToRepost],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> publishRightToBeForgotten() => (super.noSuchMethod(
        Invocation.method(
          #publishRightToBeForgotten,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [VideoEventService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoEventService extends _i1.Mock implements _i10.VideoEventService {
  MockVideoEventService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i11.VideoEvent> get homeFeedVideos => (super.noSuchMethod(
        Invocation.getter(#homeFeedVideos),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  List<_i11.VideoEvent> get discoveryVideos => (super.noSuchMethod(
        Invocation.getter(#discoveryVideos),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  List<_i11.VideoEvent> get profileVideos => (super.noSuchMethod(
        Invocation.getter(#profileVideos),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  List<_i11.VideoEvent> get editorialVideos => (super.noSuchMethod(
        Invocation.getter(#editorialVideos),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  List<_i11.VideoEvent> get popularNowVideos => (super.noSuchMethod(
        Invocation.getter(#popularNowVideos),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  List<_i11.VideoEvent> get trendingVideos => (super.noSuchMethod(
        Invocation.getter(#trendingVideos),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  List<_i11.VideoEvent> get hashtagVideos => (super.noSuchMethod(
        Invocation.getter(#hashtagVideos),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  List<_i11.VideoEvent> get searchResults => (super.noSuchMethod(
        Invocation.getter(#searchResults),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  List<_i11.VideoEvent> get videoEvents => (super.noSuchMethod(
        Invocation.getter(#videoEvents),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  String get classicVinesPubkey => (super.noSuchMethod(
        Invocation.getter(#classicVinesPubkey),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#classicVinesPubkey),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setBlocklistService(_i12.ContentBlocklistService? blocklistService) =>
      super.noSuchMethod(
        Invocation.method(
          #setBlocklistService,
          [blocklistService],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i11.VideoEvent> getVideos(_i10.SubscriptionType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideos,
          [type],
        ),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  bool hasEvents(_i10.SubscriptionType? type) => (super.noSuchMethod(
        Invocation.method(
          #hasEvents,
          [type],
        ),
        returnValue: false,
      ) as bool);

  @override
  int getEventCount(_i10.SubscriptionType? type) => (super.noSuchMethod(
        Invocation.method(
          #getEventCount,
          [type],
        ),
        returnValue: 0,
      ) as int);

  @override
  bool isSubscribed(_i10.SubscriptionType? type) => (super.noSuchMethod(
        Invocation.method(
          #isSubscribed,
          [type],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<_i11.VideoEvent> getVideosByAuthor(String? pubkey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideosByAuthor,
          [pubkey],
        ),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  _i3.Future<void> subscribeToVideoFeed({
    required _i10.SubscriptionType? subscriptionType,
    List<String>? authors,
    List<String>? hashtags,
    String? group,
    int? since,
    int? until,
    int? limit = 50,
    bool? replace = true,
    bool? includeReposts = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToVideoFeed,
          [],
          {
            #subscriptionType: subscriptionType,
            #authors: authors,
            #hashtags: hashtags,
            #group: group,
            #since: since,
            #until: until,
            #limit: limit,
            #replace: replace,
            #includeReposts: includeReposts,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> subscribeToUserVideos(
    String? pubkey, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToUserVideos,
          [pubkey],
          {#limit: limit},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> subscribeToHashtagVideos(
    List<String>? hashtags, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToHashtagVideos,
          [hashtags],
          {#limit: limit},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> subscribeToHomeFeed(
    List<String>? followingPubkeys, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToHomeFeed,
          [followingPubkeys],
          {#limit: limit},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> subscribeToDiscovery({int? limit = 100}) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToDiscovery,
          [],
          {#limit: limit},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> subscribeToGroupVideos(
    String? group, {
    List<String>? authors,
    int? since,
    int? until,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToGroupVideos,
          [group],
          {
            #authors: authors,
            #since: since,
            #until: until,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i11.VideoEvent> getVideoEventsByGroup(String? group) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoEventsByGroup,
          [group],
        ),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  _i3.Future<void> refreshVideoFeed() => (super.noSuchMethod(
        Invocation.method(
          #refreshVideoFeed,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> loadMoreVideos({int? limit = 100}) => (super.noSuchMethod(
        Invocation.method(
          #loadMoreVideos,
          [],
          {#limit: limit},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> loadMoreEvents(
    _i10.SubscriptionType? subscriptionType, {
    int? limit = 200,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMoreEvents,
          [subscriptionType],
          {#limit: limit},
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> loadMoreContentUnlimited({
    _i10.SubscriptionType? subscriptionType = _i10.SubscriptionType.discovery,
    int? limit = 300,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMoreContentUnlimited,
          [],
          {
            #subscriptionType: subscriptionType,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i11.VideoEvent? getVideoEventById(String? eventId) =>
      (super.noSuchMethod(Invocation.method(
        #getVideoEventById,
        [eventId],
      )) as _i11.VideoEvent?);

  @override
  _i11.VideoEvent? getVideoEventByVineId(String? vineId) =>
      (super.noSuchMethod(Invocation.method(
        #getVideoEventByVineId,
        [vineId],
      )) as _i11.VideoEvent?);

  @override
  _i3.Future<_i11.VideoEvent?> queryVideoByVineId(String? vineId) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryVideoByVineId,
          [vineId],
        ),
        returnValue: _i3.Future<_i11.VideoEvent?>.value(),
      ) as _i3.Future<_i11.VideoEvent?>);

  @override
  List<_i11.VideoEvent> getVideoEventsByAuthor(String? pubkey) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoEventsByAuthor,
          [pubkey],
        ),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  List<_i11.VideoEvent> getVideoEventsByHashtags(List<String>? hashtags) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoEventsByHashtags,
          [hashtags],
        ),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  void clearVideoEvents() => super.noSuchMethod(
        Invocation.method(
          #clearVideoEvents,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> unsubscribeFromVideoFeed() => (super.noSuchMethod(
        Invocation.method(
          #unsubscribeFromVideoFeed,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<_i11.VideoEvent> getVideoEventsByEngagement() => (super.noSuchMethod(
        Invocation.method(
          #getVideoEventsByEngagement,
          [],
        ),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  List<_i11.VideoEvent> getRecentVideoEvents({int? hours = 24}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentVideoEvents,
          [],
          {#hours: hours},
        ),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  Set<String> getUniqueAuthors() => (super.noSuchMethod(
        Invocation.method(
          #getUniqueAuthors,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Set<String> getAllHashtags() => (super.noSuchMethod(
        Invocation.method(
          #getAllHashtags,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Map<String, int> getVideoCountByAuthor() => (super.noSuchMethod(
        Invocation.method(
          #getVideoCountByAuthor,
          [],
        ),
        returnValue: <String, int>{},
      ) as Map<String, int>);

  @override
  Map<String, dynamic> getConnectionStatus() => (super.noSuchMethod(
        Invocation.method(
          #getConnectionStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i3.Future<void> retrySubscription() => (super.noSuchMethod(
        Invocation.method(
          #retrySubscription,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void shuffleForDiscovery() => super.noSuchMethod(
        Invocation.method(
          #shuffleForDiscovery,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addVideoEvent(_i11.VideoEvent? videoEvent) => super.noSuchMethod(
        Invocation.method(
          #addVideoEvent,
          [videoEvent],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVideos,
          [query],
          {
            #authors: authors,
            #since: since,
            #until: until,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> searchVideosByHashtag(String? hashtag) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVideosByHashtag,
          [hashtag],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> searchVideosWithFilters({
    required String? query,
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVideosWithFilters,
          [],
          {
            #query: query,
            #authors: authors,
            #since: since,
            #until: until,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void clearSearchResults() => super.noSuchMethod(
        Invocation.method(
          #clearSearchResults,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i11.VideoEvent> processSearchResults(List<_i5.Event>? events) =>
      (super.noSuchMethod(
        Invocation.method(
          #processSearchResults,
          [events],
        ),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  List<_i11.VideoEvent> deduplicateSearchResults(
          List<_i11.VideoEvent>? results) =>
      (super.noSuchMethod(
        Invocation.method(
          #deduplicateSearchResults,
          [results],
        ),
        returnValue: <_i11.VideoEvent>[],
      ) as List<_i11.VideoEvent>);

  @override
  _i3.Future<void> searchVideosWithTimeRange({
    required String? query,
    required DateTime? since,
    required DateTime? until,
    List<String>? authors,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVideosWithTimeRange,
          [],
          {
            #query: query,
            #since: since,
            #until: until,
            #authors: authors,
            #limit: limit,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> searchVideosWithExtensions(String? queryWithExtensions) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVideosWithExtensions,
          [queryWithExtensions],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  Map<_i10.SubscriptionType, _i10.PaginationState>
      getPaginationStatesForTesting() => (super.noSuchMethod(
            Invocation.method(
              #getPaginationStatesForTesting,
              [],
            ),
            returnValue: <_i10.SubscriptionType, _i10.PaginationState>{},
          ) as Map<_i10.SubscriptionType, _i10.PaginationState>);

  @override
  void addVideoEventForTesting(
    _i11.VideoEvent? event,
    _i10.SubscriptionType? type, {
    required bool? isHistorical,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addVideoEventForTesting,
          [
            event,
            type,
          ],
          {#isHistorical: isHistorical},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
