// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/widgets/settings_screen_scaffold_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nostr_sdk/event.dart' as _i5;
import 'package:openvine/services/auth_service.dart' as _i2;
import 'package:openvine/services/user_profile_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _i2.AuthState.unauthenticated,
          )
          as _i2.AuthState);

  @override
  _i3.Stream<_i2.AuthState> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i3.Stream<_i2.AuthState>.empty(),
          )
          as _i3.Stream<_i2.AuthState>);

  @override
  _i3.Stream<_i2.UserProfile?> get profileStream =>
      (super.noSuchMethod(
            Invocation.getter(#profileStream),
            returnValue: _i3.Stream<_i2.UserProfile?>.empty(),
          )
          as _i3.Stream<_i2.UserProfile?>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> get userStats =>
      (super.noSuchMethod(
            Invocation.getter(#userStats),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i2.AuthResult> createNewIdentity({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#createNewIdentity, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i3.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#createNewIdentity, [], {
                  #biometricPrompt: biometricPrompt,
                }),
              ),
            ),
          )
          as _i3.Future<_i2.AuthResult>);

  @override
  _i3.Future<_i2.AuthResult> importFromNsec(
    String? nsec, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromNsec,
              [nsec],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i3.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromNsec,
                  [nsec],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i3.Future<_i2.AuthResult>);

  @override
  _i3.Future<_i2.AuthResult> importFromHex(
    String? privateKeyHex, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromHex,
              [privateKeyHex],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i3.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromHex,
                  [privateKeyHex],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i3.Future<_i2.AuthResult>);

  @override
  _i3.Future<void> refreshCurrentProfile(
    _i4.UserProfileService? userProfileService,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentProfile, [userProfileService]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> acceptTermsOfService() =>
      (super.noSuchMethod(
            Invocation.method(#acceptTermsOfService, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> signOut({bool? deleteKeys = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#deleteKeys: deleteKeys}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getPrivateKeyForSigning({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateKeyForSigning, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> exportNsec({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#exportNsec, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<_i5.Event?> createAndSignEvent({
    required int? kind,
    required String? content,
    List<List<String>>? tags,
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAndSignEvent, [], {
              #kind: kind,
              #content: content,
              #tags: tags,
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i3.Future<_i5.Event?>.value(),
          )
          as _i3.Future<_i5.Event?>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
