// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/widgets/tabbed_settings_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i14;

import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:models/models.dart' as _i7;
import 'package:nostr_client/nostr_client.dart' as _i11;
import 'package:nostr_client/src/models/models.dart' as _i3;
import 'package:nostr_sdk/event.dart' as _i10;
import 'package:nostr_sdk/nostr_sdk.dart' as _i13;
import 'package:openvine/models/bug_report_data.dart' as _i6;
import 'package:openvine/models/notification_model.dart' as _i16;
import 'package:openvine/services/auth_service.dart' as _i2;
import 'package:openvine/services/blossom_upload_service.dart' as _i5;
import 'package:openvine/services/bug_report_service.dart' as _i18;
import 'package:openvine/services/notification_service_enhanced.dart' as _i15;
import 'package:openvine/services/user_profile_service.dart' as _i9;
import 'package:openvine/services/video_event_service.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthResult_0 extends _i1.SmartFake implements _i2.AuthResult {
  _FakeAuthResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCountResult_1 extends _i1.SmartFake implements _i3.CountResult {
  _FakeCountResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrBroadcastResult_2 extends _i1.SmartFake
    implements _i3.NostrBroadcastResult {
  _FakeNostrBroadcastResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_3 extends _i1.SmartFake implements _i2.AuthService {
  _FakeAuthService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_4 extends _i1.SmartFake implements _i4.Dio {
  _FakeDio_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBlossomUploadResult_5 extends _i1.SmartFake
    implements _i5.BlossomUploadResult {
  _FakeBlossomUploadResult_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBugReportData_6 extends _i1.SmartFake implements _i6.BugReportData {
  _FakeBugReportData_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBugReportResult_7 extends _i1.SmartFake
    implements _i7.BugReportResult {
  _FakeBugReportResult_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get authState =>
      (super.noSuchMethod(
            Invocation.getter(#authState),
            returnValue: _i2.AuthState.unauthenticated,
          )
          as _i2.AuthState);

  @override
  _i8.Stream<_i2.AuthState> get authStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#authStateStream),
            returnValue: _i8.Stream<_i2.AuthState>.empty(),
          )
          as _i8.Stream<_i2.AuthState>);

  @override
  _i8.Stream<_i2.UserProfile?> get profileStream =>
      (super.noSuchMethod(
            Invocation.getter(#profileStream),
            returnValue: _i8.Stream<_i2.UserProfile?>.empty(),
          )
          as _i8.Stream<_i2.UserProfile?>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, dynamic> get userStats =>
      (super.noSuchMethod(
            Invocation.getter(#userStats),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i8.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.AuthResult> createNewIdentity({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#createNewIdentity, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i8.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(#createNewIdentity, [], {
                  #biometricPrompt: biometricPrompt,
                }),
              ),
            ),
          )
          as _i8.Future<_i2.AuthResult>);

  @override
  _i8.Future<_i2.AuthResult> importFromNsec(
    String? nsec, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromNsec,
              [nsec],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i8.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromNsec,
                  [nsec],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.AuthResult>);

  @override
  _i8.Future<_i2.AuthResult> importFromHex(
    String? privateKeyHex, {
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #importFromHex,
              [privateKeyHex],
              {#biometricPrompt: biometricPrompt},
            ),
            returnValue: _i8.Future<_i2.AuthResult>.value(
              _FakeAuthResult_0(
                this,
                Invocation.method(
                  #importFromHex,
                  [privateKeyHex],
                  {#biometricPrompt: biometricPrompt},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.AuthResult>);

  @override
  _i8.Future<void> refreshCurrentProfile(
    _i9.UserProfileService? userProfileService,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentProfile, [userProfileService]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> acceptTermsOfService() =>
      (super.noSuchMethod(
            Invocation.method(#acceptTermsOfService, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> signOut({bool? deleteKeys = false}) =>
      (super.noSuchMethod(
            Invocation.method(#signOut, [], {#deleteKeys: deleteKeys}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getPrivateKeyForSigning({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#getPrivateKeyForSigning, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<String?> exportNsec({String? biometricPrompt}) =>
      (super.noSuchMethod(
            Invocation.method(#exportNsec, [], {
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<_i10.Event?> createAndSignEvent({
    required int? kind,
    required String? content,
    List<List<String>>? tags,
    String? biometricPrompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAndSignEvent, [], {
              #kind: kind,
              #content: content,
              #tags: tags,
              #biometricPrompt: biometricPrompt,
            }),
            returnValue: _i8.Future<_i10.Event?>.value(),
          )
          as _i8.Future<_i10.Event?>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NostrClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrClient extends _i1.Mock implements _i11.NostrClient {
  MockNostrClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#publicKey),
            ),
          )
          as String);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  List<String> get configuredRelays =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get connectedRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  int get configuredRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  Map<String, _i3.RelayConnectionStatus> get relayStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatuses),
            returnValue: <String, _i3.RelayConnectionStatus>{},
          )
          as Map<String, _i3.RelayConnectionStatus>);

  @override
  _i8.Stream<Map<String, _i3.RelayConnectionStatus>> get relayStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatusStream),
            returnValue:
                _i8.Stream<Map<String, _i3.RelayConnectionStatus>>.empty(),
          )
          as _i8.Stream<Map<String, _i3.RelayConnectionStatus>>);

  @override
  String get primaryRelay =>
      (super.noSuchMethod(
            Invocation.getter(#primaryRelay),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.getter(#primaryRelay),
            ),
          )
          as String);

  @override
  _i8.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i10.Event?> publishEvent(
    _i10.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #publishEvent,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i8.Future<_i10.Event?>.value(),
          )
          as _i8.Future<_i10.Event?>);

  @override
  _i8.Future<List<_i10.Event>> queryEvents(
    List<_i13.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #useGateway: useGateway,
                #useCache: useCache,
              },
            ),
            returnValue: _i8.Future<List<_i10.Event>>.value(<_i10.Event>[]),
          )
          as _i8.Future<List<_i10.Event>>);

  @override
  _i8.Future<_i3.CountResult> countEvents(
    List<_i13.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #countEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #timeout: timeout,
              },
            ),
            returnValue: _i8.Future<_i3.CountResult>.value(
              _FakeCountResult_1(
                this,
                Invocation.method(
                  #countEvents,
                  [filters],
                  {
                    #subscriptionId: subscriptionId,
                    #tempRelays: tempRelays,
                    #relayTypes: relayTypes,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i3.CountResult>);

  @override
  _i8.Future<_i10.Event?> fetchEventById(
    String? eventId, {
    String? relayUrl,
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEventById,
              [eventId],
              {
                #relayUrl: relayUrl,
                #useGateway: useGateway,
                #useCache: useCache,
              },
            ),
            returnValue: _i8.Future<_i10.Event?>.value(),
          )
          as _i8.Future<_i10.Event?>);

  @override
  _i8.Future<_i10.Event?> fetchProfile(
    String? pubkey, {
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchProfile,
              [pubkey],
              {#useGateway: useGateway, #useCache: useCache},
            ),
            returnValue: _i8.Future<_i10.Event?>.value(),
          )
          as _i8.Future<_i10.Event?>);

  @override
  _i8.Stream<_i10.Event> subscribe(
    List<_i13.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribe,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #onEose: onEose,
              },
            ),
            returnValue: _i8.Stream<_i10.Event>.empty(),
          )
          as _i8.Stream<_i10.Event>);

  @override
  _i8.Future<void> unsubscribe(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [subscriptionId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> closeAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#closeAllSubscriptions, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> addRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#addRelay, [relayUrl]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> removeRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelay, [relayUrl]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<Map<String, dynamic>?> getRelayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStats, []),
            returnValue: _i8.Future<Map<String, dynamic>?>.value(),
          )
          as _i8.Future<Map<String, dynamic>?>);

  @override
  _i8.Future<void> retryDisconnectedRelays() =>
      (super.noSuchMethod(
            Invocation.method(#retryDisconnectedRelays, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  Map<String, bool> getRelayStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStatus, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i8.Future<_i10.Event?> sendLike(
    String? eventId, {
    String? content,
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendLike,
              [eventId],
              {
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i8.Future<_i10.Event?>.value(),
          )
          as _i8.Future<_i10.Event?>);

  @override
  _i8.Future<_i10.Event?> sendRepost(
    String? eventId, {
    String? relayAddr,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendRepost,
              [eventId],
              {
                #relayAddr: relayAddr,
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i8.Future<_i10.Event?>.value(),
          )
          as _i8.Future<_i10.Event?>);

  @override
  _i8.Future<_i10.Event?> deleteEvent(
    String? eventId, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvent,
              [eventId],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i8.Future<_i10.Event?>.value(),
          )
          as _i8.Future<_i10.Event?>);

  @override
  _i8.Future<_i10.Event?> deleteEvents(
    List<String>? eventIds, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvents,
              [eventIds],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i8.Future<_i10.Event?>.value(),
          )
          as _i8.Future<_i10.Event?>);

  @override
  _i8.Future<_i10.Event?> sendContactList(
    _i13.ContactList? contacts,
    String? content, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendContactList,
              [contacts, content],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i8.Future<_i10.Event?>.value(),
          )
          as _i8.Future<_i10.Event?>);

  @override
  _i8.Stream<_i10.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i8.Stream<_i10.Event>.empty(),
          )
          as _i8.Stream<_i10.Event>);

  @override
  _i8.Stream<_i10.Event> searchUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i8.Stream<_i10.Event>.empty(),
          )
          as _i8.Stream<_i10.Event>);

  @override
  _i8.Future<_i3.NostrBroadcastResult> broadcast(
    _i10.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #broadcast,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i8.Future<_i3.NostrBroadcastResult>.value(
              _FakeNostrBroadcastResult_2(
                this,
                Invocation.method(
                  #broadcast,
                  [event],
                  {#targetRelays: targetRelays},
                ),
              ),
            ),
          )
          as _i8.Future<_i3.NostrBroadcastResult>);

  @override
  _i8.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [BlossomUploadService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlossomUploadService extends _i1.Mock
    implements _i5.BlossomUploadService {
  MockBlossomUploadService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_3(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i2.AuthService);

  @override
  _i4.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_4(this, Invocation.getter(#dio)),
          )
          as _i4.Dio);

  @override
  _i8.Future<String?> getBlossomServer() =>
      (super.noSuchMethod(
            Invocation.method(#getBlossomServer, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> setBlossomServer(String? serverUrl) =>
      (super.noSuchMethod(
            Invocation.method(#setBlossomServer, [serverUrl]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isBlossomEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isBlossomEnabled, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> setBlossomEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setBlossomEnabled, [enabled]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i5.BlossomUploadResult> uploadVideo({
    required _i14.File? videoFile,
    required String? nostrPubkey,
    required String? title,
    String? description,
    List<String>? hashtags,
    String? proofManifestJson,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadVideo, [], {
              #videoFile: videoFile,
              #nostrPubkey: nostrPubkey,
              #title: title,
              #description: description,
              #hashtags: hashtags,
              #proofManifestJson: proofManifestJson,
              #onProgress: onProgress,
            }),
            returnValue: _i8.Future<_i5.BlossomUploadResult>.value(
              _FakeBlossomUploadResult_5(
                this,
                Invocation.method(#uploadVideo, [], {
                  #videoFile: videoFile,
                  #nostrPubkey: nostrPubkey,
                  #title: title,
                  #description: description,
                  #hashtags: hashtags,
                  #proofManifestJson: proofManifestJson,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.BlossomUploadResult>);

  @override
  _i8.Future<_i5.BlossomUploadResult> uploadImage({
    required _i14.File? imageFile,
    required String? nostrPubkey,
    String? mimeType = 'image/jpeg',
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [], {
              #imageFile: imageFile,
              #nostrPubkey: nostrPubkey,
              #mimeType: mimeType,
              #onProgress: onProgress,
            }),
            returnValue: _i8.Future<_i5.BlossomUploadResult>.value(
              _FakeBlossomUploadResult_5(
                this,
                Invocation.method(#uploadImage, [], {
                  #imageFile: imageFile,
                  #nostrPubkey: nostrPubkey,
                  #mimeType: mimeType,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i8.Future<_i5.BlossomUploadResult>);

  @override
  _i8.Future<String?> uploadBugReport({
    required _i14.File? bugReportFile,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadBugReport, [], {
              #bugReportFile: bugReportFile,
              #onProgress: onProgress,
            }),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);
}

/// A class which mocks [NotificationServiceEnhanced].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationServiceEnhanced extends _i1.Mock
    implements _i15.NotificationServiceEnhanced {
  MockNotificationServiceEnhanced() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i16.NotificationModel> get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: <_i16.NotificationModel>[],
          )
          as List<_i16.NotificationModel>);

  @override
  int get unreadCount =>
      (super.noSuchMethod(Invocation.getter(#unreadCount), returnValue: 0)
          as int);

  @override
  bool get hasPermissions =>
      (super.noSuchMethod(
            Invocation.getter(#hasPermissions),
            returnValue: false,
          )
          as bool);

  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);

  @override
  _i8.Future<void> initialize({
    required _i11.NostrClient? nostrService,
    required _i9.UserProfileService? profileService,
    required _i17.VideoEventService? videoService,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #nostrService: nostrService,
              #profileService: profileService,
              #videoService: videoService,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> addNotificationForTesting(
    _i16.NotificationModel? notification,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addNotificationForTesting, [notification]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> markAsRead(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [notificationId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> handleNotificationTap(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#handleNotificationTap, [notificationId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  List<_i16.NotificationModel> getNotificationsByType(
    _i16.NotificationType? type,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationsByType, [type]),
            returnValue: <_i16.NotificationModel>[],
          )
          as List<_i16.NotificationModel>);

  @override
  _i8.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearOlderThan(Duration? duration) =>
      (super.noSuchMethod(
            Invocation.method(#clearOlderThan, [duration]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> refreshNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#refreshNotifications, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BugReportService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBugReportService extends _i1.Mock implements _i18.BugReportService {
  MockBugReportService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.BugReportData> collectDiagnostics({
    required String? userDescription,
    String? currentScreen,
    String? userPubkey,
    Map<String, dynamic>? additionalContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#collectDiagnostics, [], {
              #userDescription: userDescription,
              #currentScreen: currentScreen,
              #userPubkey: userPubkey,
              #additionalContext: additionalContext,
            }),
            returnValue: _i8.Future<_i6.BugReportData>.value(
              _FakeBugReportData_6(
                this,
                Invocation.method(#collectDiagnostics, [], {
                  #userDescription: userDescription,
                  #currentScreen: currentScreen,
                  #userPubkey: userPubkey,
                  #additionalContext: additionalContext,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.BugReportData>);

  @override
  _i6.BugReportData sanitizeSensitiveData(_i6.BugReportData? data) =>
      (super.noSuchMethod(
            Invocation.method(#sanitizeSensitiveData, [data]),
            returnValue: _FakeBugReportData_6(
              this,
              Invocation.method(#sanitizeSensitiveData, [data]),
            ),
          )
          as _i6.BugReportData);

  @override
  int estimateReportSize(_i6.BugReportData? data) =>
      (super.noSuchMethod(
            Invocation.method(#estimateReportSize, [data]),
            returnValue: 0,
          )
          as int);

  @override
  _i8.Future<_i7.BugReportResult> sendBugReport(_i6.BugReportData? data) =>
      (super.noSuchMethod(
            Invocation.method(#sendBugReport, [data]),
            returnValue: _i8.Future<_i7.BugReportResult>.value(
              _FakeBugReportResult_7(
                this,
                Invocation.method(#sendBugReport, [data]),
              ),
            ),
          )
          as _i8.Future<_i7.BugReportResult>);

  @override
  _i8.Future<_i7.BugReportResult> sendBugReportToRecipient(
    _i6.BugReportData? data,
    String? recipientPubkey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendBugReportToRecipient, [
              data,
              recipientPubkey,
            ]),
            returnValue: _i8.Future<_i7.BugReportResult>.value(
              _FakeBugReportResult_7(
                this,
                Invocation.method(#sendBugReportToRecipient, [
                  data,
                  recipientPubkey,
                ]),
              ),
            ),
          )
          as _i8.Future<_i7.BugReportResult>);

  @override
  _i8.Future<_i7.BugReportResult> sendBugReportViaEmail(
    _i6.BugReportData? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendBugReportViaEmail, [data]),
            returnValue: _i8.Future<_i7.BugReportResult>.value(
              _FakeBugReportResult_7(
                this,
                Invocation.method(#sendBugReportViaEmail, [data]),
              ),
            ),
          )
          as _i8.Future<_i7.BugReportResult>);

  @override
  _i8.Future<bool> exportLogsToFile({
    String? currentScreen,
    String? userPubkey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#exportLogsToFile, [], {
              #currentScreen: currentScreen,
              #userPubkey: userPubkey,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);
}
